### ISSUE TITLE
Probably should be a discussion but you don't have it turned on...

### ISSUE THREAD

**Issue by josh-gree** [mvt-project/mvt#1]
Any reason you haven't put this under https://github.com/amnesty? Think that would be a good idea really just as an example;

https://twitter.com/Hammered_Glass/status/1416828070804271105?s=20 

And

https://twitter.com/danielyang92/status/1416876353794813962?s=20

I know some people will never be happy but seems like starting a whole new org is maybe unhelpful...

**Comment by josh-gree** [comment]
@Te-k you even have this Org https://github.com/AmnestyTech - why not put it there?

**Comment by Te-k** [comment]
Hi, for many reasons, we decided to have this project in a separate group, but I have updated the README to explain that it was released by Amnesty with a link to the report
