### ISSUE TITLE
Make a windows version please

### ISSUE THREAD

**Issue by BimboPolitics** [mvt-project/mvt#10]
Most people use windows as their main OS and find linux confusing. If you want the most people possible to check their devices for this stuff you need a tool that works on the operating system they use.

**Comment by alexmyczko** [comment]
Maybe that is not what the author wants? And how can you know most people do not use Linux? or macOS? Besides Windows has Linux meanwhile called WSL, so it should be no problem to use it there.

**Comment by BimboPolitics** [comment]
https://www.statista.com/statistics/218089/global-market-share-of-windows-7/

This was simple enough to look up and you should have done it first before asking.

**Comment by kinostl** [comment]
The average user is intimidated by the command line and multi-step processes. The average user is scared of documentation that exists outside of the program. They expect a wizard to download APKs, and a basic GUI interface for all of the available commands.

Since this is a python project, something such as [Gooey](https://github.com/chriskiehl/Gooey) could be incorporated to make this an easy process.

This is a very useful project that should be as portable as possible, especially with the recent media coverage.

**Comment by alexmyczko** [comment]
> https://www.statista.com/statistics/218089/global-market-share-of-windows-7/

Not sure who these statista.com people are, but they lie, according to this source about server software:

https://news.netcraft.com/archives/category/web-server-survey/

Windows 7? Whoever runs an OS that doesn't get security support anymore, is like driving a car or flying a plane without servicing it. A danger to others.

https://www.top500.org/statistics/list/ that one is also nice, sort by Category:Operating System

> This was simple enough to look up and you should have done it first before asking.

The problem is not looking something up. But something that could vaguely be true.

**Comment by BimboPolitics** [comment]
From the article you clearly did not read 

"Microsoft Windows is the dominating desktop operating system (OS) worldwide as of June 2021, with a share of just under 73 percent."

We arent talking about servers. Were talking about desktops. Which is what normal people use. The same people who may want to check their phones for malware.

**Comment by alexmyczko** [comment]
You missed my point, if they are factor 5 wrong with the servers. How can you be sure they are not wrong with the clients?

**Comment by alexmyczko** [comment]
The people there are not doing their homework right, and if the claim numbers, where's the details how they got to those numbers? It's like random person appears, on random webpage, says some numbers and a claim, and people believe it? Please...

> Operating systems market share of desktop PCs 2013-2021, by month
> Published by Shanhong Liu, Jul 9, 2021
>  Microsoft Windows is the dominating desktop operating system (OS) worldwide as of June 2021, with a share of just under 73 percent. Apple’s Mac operating system has been gaining market share over the years, albeit remaining a minor player in the desktop OS market. Linus, the third most popular desktop OS, has a small but stable share of the market. 
> Different versions of Microsoft Windows
> From its initial release in 1985, Microsoft Windows has gone through endless mutations. Notable versions include Windows 95, Windows XP, and Windows 7. Windows 10 is the newest addition to the family, being able to run on PCs, tablets and embedded devices. Windows is also the server computer OS with the largest market share of over 72 percent in 2019. 

> Apple’s Mac operating system
> Having an equally long history, Apple’s Mac operating system (macOS, previously Mac OS X and OS X) also went through different releases. The most recent version macOS Catalina (version 10.15) is the sixteenth release of macOS. Released in October 2019, macOS Catalina is now run on almost 74.5 percent of the Apple computers as of June 2021. macOS runs on Apple’s Mac computers, including the MacBook, which is Apple’s laptop PC product including the MacBook Pro and MacBook Air, and the iMac – Apple’s desktop computer.
> 

macOS Catalina https://en.wikipedia.org/wiki/MacOS_Catalina clearly is not the most recent version since 8+ months.

**Comment by BimboPolitics** [comment]
Do you. Seriously. Think most regular people. Dont use windows? For real? Are you that much in your linux bubble? "Most people use windows desktop" is not a controversial statement lol

**Comment by alexmyczko** [comment]
Seriously, the people that play games, use a console or Windows. Those that need to get work done use macOS. No idea about the numbers. Waiting for Apple and Microsoft to communicate the numbers (they surely have stats on sales and access logs to their update servers)

**Comment by Zanthed** [comment]
@alexmyczko @BimboPolitics 
This should not a discussion of "which OS is the most popular". Please stop this. It's not productive at all.

The real concern should be "why is this not operating system agnostic".
Have you actually tested this on Windows? This is a Python script. Unless the code in it is written for *NIX only, there should not be any reason why this cannot run on Windows. Just follow official Python installation process and test this yourself.

**Comment by BimboPolitics** [comment]
> @alexmyczko @BimboPolitics
> This should not a discussion of "which OS is the most popular". Please stop this. It's not productive at all.
> 
> The real concern should be "why is this not operating system agnostic".
> Have you actually tested this on Windows? This is a Python script. Unless the code in it is written for *NIX only, there should not be any reason why this cannot run on Windows. Just follow official Python installation process and test this yourself.
> 
> If you find that the script is not OS agnostic, please report the problem in a separate issue.

Do you genuinely think the average person having seen the media coverage of the problem and this app billed as its solution is going to be able to do that? When making tools like this developers have to put themselves in the shoes of the people who may use it. With something this important, IE state actors targeting activists and the like, who may not be specialized in infosec the tools need to be easy to use. 

I promise you if theres not an installer they can click and then click on something to run it they are just going to give up in frustration.

You cannot force them to change this, you can only choose to adapt to it or not.

**Comment by Abraxis-Sutur** [comment]
Could this be the first time anyone's thought to bicker about operating system preferences on the internet? 🥱

**Comment by d33pk3rn3l** [comment]
**python3 and libusb both do work on Windows. I see it the same as @Zanthed, please test it on your machine. If it doesn‘t work, open an Issue stating where it breaks and somebody can fix it.** 

As a sidenote: This tool is not for the everyday user to „to check their devices for this stuff“. I’m sorry if you read this in the media. Also making „installers they can click on“ has implications on this very sensitive topic of letting software go through your once encrypted backup. Think about it like letting somebody on the street that (might’ve) showed you a badge going through almost every single bit of your personal data. With a solution like this you can be sure relatively easily (beforehand!) what this cop will do. Nevertheless, feel free to fork and make (or pay somebody to make) a GUI and installer for Windows. That‘s the beauty of open source!

!Vote close this issue

**Comment by wchristian** [comment]
I see a lot of people who aren't @Te-k trying to reject this improvement request in their stead without citing anything said by them.

**Comment by Zanthed** [comment]
@BimboPolitics 

> I promise you if theres not an installer they can click and then click on something to run it they are just going to give up in frustration.

This is a forensics tool using Python. It assumes you are already knowledgeable in forensics and computer security. There will not be a "one click installer" whether you like it or not.

This tool should not have been posted on mainstream media to avoid silly questions like these.

@botherder @Te-k 
This issue needs to be closed and locked to avoid further heated and unproductive discussion.

**Comment by josh-gree** [comment]
> This tool should not have been posted on mainstream media to avoid silly questions like these.

Talk about gate keeping!

**Comment by lotsofnoise** [comment]
> Most people use windows as their main OS and find linux confusing. If you want the most people possible to check their devices for this stuff you need a tool that works on the operating system they use.

Here's an [iOS/Windows] tutorial:
https://fervent-golick-5a7145.netlify.app

**Comment by scorchgid** [comment]
> Maybe that is not what the author wants? And how can you know most people do not use Linux? or macOS? Besides Windows has Linux meanwhile called WSL, so it should be no problem to use it there.

Because I don't and now I have to dig out my out Linux laptop to do it. So yeah it's a bit annoying

**Comment by JoeUX** [comment]
I don't think it's a silly question, given that Windows 10 and its predecessors are the most popular desktop OSes worldwide. This only gets more true outside of the US, but it's a large margin even inside the US. I think the idea of experimenting with the Python script on Windows is fine, but note that the documentation implies to most people that Windows is not supported. Linux and macOS are mentioned explicitly, but there's no mention of Windows at all, even to say that it's not supported.

I wouldn't assume that the more technically proficient would all choose to buy desktop computers that can't be upgraded by their owners, or an OS that embedded insecure software like Git at a low level and locked it in, or to be willing to support companies like Apple in general. Especially given the scale of the market we're talking about. There will be millions and millions of pros using Windows. And in forensics this is even more true – major applications like EnCase and Magnet Axiom only run on Windows. Forensics isn't known for being a non-Windows profession at all.

Anything that requires the installation of so much other software is suboptimal. Having to install Python itself, an old-fashioned interpreter, is a hard sell and a security problem. A normal, compiled program is much cleaner, so longer term something written in Go, C#, etc. would be a lot easier to distribute – something that can be compiled into a program.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@lotsofnoise In my case with Android phone I used [WinPython](https://winpython.github.io/) and ADB from [Chocolatey repository](https://community.chocolatey.org/packages/adb). Before running the script don't forget to authorize the phone via `adb shell` and `adb kill-server`, otherwise annoying nags will constantly pop up.

**Comment by Liebelts** [comment]
I just tried on Windows 7 and it works fine (at least  `mvt-android download-apks` ). The only difference is that i had to do some tweaking with adb like aeiouaeiouaeiouaeiouaeiouaeiou said above.

**Comment by Zanthed** [comment]
As users have reported, this works just fine on Windows.
The "Windows version" you're requesting already exists.

**Comment by heathmcd** [comment]
> As users have reported, this works just fine on Windows.
> The "Windows version" you're requesting already exists.

This is why everyone hates Linux users.

**Comment by Te-k** [comment]
Hi, thanks for taking part to this discussion.

mvt won't ever be an click and run and easy to use tool, it is not done for that, it is done for a technical audience who understands forensic and how to interpret results. That's why it is only released with a technical methodology and only as a CLI tool.

That said, we welcome people improving the tool and documentation and fixing bugs on Windows, feel free to open tickets or submit PRs. In the same way, if some people want to make a GUI of mvt, we don't see any issue with that, it is likely better to make a different project using the mvt as an API to avoid overloading mvt.

For the sake of keeping this list focused on improvements and bugs, I am going to close this ticket.
