### ISSUE TITLE
mvt-android is not working with wireless adb

### ISSUE THREAD

**Issue by Alpha272** [mvt-project/mvt#107]
When I connect an Android device with wireless adb (adb connect \<ip\>:5555) mvt recognizes that an Android device is available but errors out, since it assumes that the Android device is connected via USB. In my setup usb isn't a viable option since I need to use docker and I am unable to pass a USB device into the docker container.

![image](https://user-images.githubusercontent.com/22331613/126883725-0701e725-a954-4133-ae71-e01f75994ece.png)

Also little side note: the adb version in the docker container is outdated and doesn't support adb pair, which is used by most modern Android devices for wireless adb. (To use wireless adb in the old version you first need to connect to the Android device with usb or with a more modern adb version which supports adb pair. After that you can restart the adb deamon on the Android device with "adb tcpip 5555" and after that you can connect with adb connect from the docker container. This change is not permanent and after restarting USB debugging on the Android device the old wireless adb version is disabled again, and you need to repeat the process, if you want to connect from the old adb version again.)

**Comment by botherder** [comment]
This should now be resolved. You can now specify a connection string using `--serial`.
