### ISSUE TITLE
command mvt-android don't work

### ISSUE THREAD

**Issue by ButNobodyCloe** [mvt-project/mvt#114]
I install mvt but when I try to run it with the "mvt-android" command. I have an error : 
$ mvt-android                                            
mvt-android: command not found
(I use Kali-Linux)

i'm not really familiarized with linux, and i probably do something wrong. I search since more than one hour but i don't find a solution for solve the problem. Please help me, thank you 👍

**Comment by iofjuupasli** [comment]
you need to check https://mvt.readthedocs.io/en/latest/install.html this part:
> If you haven't done so, you can add this to your .bashrc or .zshrc file in order to add locally installed Pypi binaries to your $PATH:
export PATH=$PATH:~/.local/bin

**Comment by ButNobodyCloe** [comment]
> 
> 
> you need to check https://mvt.readthedocs.io/en/latest/install.html this part:
> 
> > If you haven't done so, you can add this to your .bashrc or .zshrc file in order to add locally installed Pypi binaries to your $PATH:
> > export PATH=$PATH:~/.local/bin


> 
> 
> you need to check https://mvt.readthedocs.io/en/latest/install.html this part:
> 
> > If you haven't done so, you can add this to your .bashrc or .zshrc file in order to add locally installed Pypi binaries to your $PATH:
> > export PATH=$PATH:~/.local/bin

I don't really understand what i can do exactly, what is the "PATH" where is it, and how install it if i need it.. I truly need help, please

**Comment by Te-k** [comment]
You need to look how to add the pypi binary folder in your path, that is where the mvt binaries are

**Comment by thepate94227** [comment]
@ButNobodyCloe try sudo pip3 install mvt
I forgot the sudo and had the same problem.

**Comment by Te-k** [comment]
Closing as it is not an mvt issue
