### ISSUE TITLE
[Documentation] MVT-iOS resourceLog.plist listed as available in backups

### ISSUE THREAD

**Issue by gregzo** [mvt-project/mvt#121]
According to our tests, the various `full_browsing_session_resourceLog.plist` files listed in the [webkit_session_resource_log](https://github.com/mvt-project/mvt/blob/main/mvt/ios/modules/fs/webkit_session_resource_log.py) module are never available in iOS backups. The [documentation](https://mvt.readthedocs.io/en/latest/ios/records.html#webkit_session_resource_logjson) classifies the files as available in both an FS dump and a backup.

**Comment by botherder** [comment]
We have seen it exported in backups, that is why we have a known backup ID for it:
https://github.com/mvt-project/mvt/blob/main/mvt/ios/modules/fs/webkit_session_resource_log.py#L15
