### ISSUE TITLE
Translate documentation into Spanish

### ISSUE THREAD

**Issue by krv00** [mvt-project/mvt#128]
Hello. Will you translate the documentation into other languages? If necessary, I can help to do it in Spanish.

**Comment by carlosm2** [comment]
the chilean collective "DIsonancia" have already translated the documentation into spanish: 
https://cdisonancia.gitlab.io/mvt-esp/

**Comment by Te-k** [comment]
That's awesome, thanks for sharing! I am not sure how to integrate that in MVT and how to keep it up-to-date. I am keeping this ticket open to discuss that

**Comment by botherder** [comment]
Closing this in favour of #260.
