### ISSUE TITLE
Possible false positive on com.apple.CrashReporter.plist

### ISSUE THREAD

**Issue by gregzo** [mvt-project/mvt#130]
`check_indicators` in [Manifest.py](https://github.com/mvt-project/mvt/blob/main/mvt/ios/modules/fs/manifest.py) explicitly checks for `com.apple.CrashReporter.plist` in the `RootDomain`. Just below, `self.indicators.check_file(result["relativePath"]):` will result in `com.apple.CrashReporter.plist` to be detected as a positive match in any domain if loading the latest STIX from the [investigations repo](https://github.com/AmnestyTech/investigations/tree/master/2021-07-18_nso)

On some of our devices, this results in what we believe is a false positive on`Library/Preferences/com.apple.CrashReporter.plist` in the `HomeDomain`. The file was seemingly created and last modified in February 2014, and can be found on 2 devices. Contents:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ShouldSubmit</key>
	<false/>
</dict>
</plist>

```

**Comment by botherder** [comment]
You are right. This file should not have ended up in the indicators list, we will have that mistake corrected.
