### ISSUE TITLE
Indicators.check_file - basename issue

### ISSUE THREAD

**Issue by macmade** [mvt-project/mvt#132]
There's a potential issue in the `check_file` method:

    file_name = os.path.basename(file_path)

I've no experience with Python, but as I understand it, `basename` will return an empty string for a path ending with a `/`, as mentioned in the documentation:

> Note that the result of this function is different from the Unix basename program; where basename for '/foo/bar/' returns 'bar', the basename() function returns an empty string ('').

The [Pegasus STIX file](https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/pegasus.stix2) contains such paths.  
For instance: `[file:name='private/var/db/com.apple.xpc.roleaccountd.staging/']`

I don't know what this is supposed to match, but as `basename` will return an empty string, it makes this kind of check useless, as far as I can tell.

**Comment by botherder** [comment]
The check is not useless, it is intended to check for file names. If a path does not contain a file name, there's no reason to check it. That indicator was actually added by mistake, and will be removed. Thank you.
