### ISSUE TITLE
WebKit Observations

### ISSUE THREAD

**Issue by macmade** [mvt-project/mvt#133]
There's maybe an interesting database to analyze on apps using WebKit on iOS.  
In an iOS backup, it's located in `AppDomain-*/Library/WebKit/WebsiteData/ResourceLoadStatistics/observations.db`

Interesting table is named `ObservedDomains`.  
Domain names are in the `registrableDomain` field.

These domains should probably be matched with the indicators.

**Comment by botherder** [comment]
Thank you for sharing this. Will look into it.

**Comment by botherder** [comment]
Closing this, as module should be created and working.
