### ISSUE TITLE
Dockerfile missing sqlite3

### ISSUE THREAD

**Issue by opsec-infosec** [mvt-project/mvt#138]
Docker image is missing sqlite3 and is unable to extract SMS messages from backups.

this issue is fixed with PR #138

**Comment by Te-k** [comment]
Thanks !

**Comment by opsec-infosec** [comment]
The dependency should probably be put under major OS Dependencies just to keep the original flow of the dockerfile

# Fixing major OS dependencies
# ----------------------------
RUN apt update \
  && apt install -y python3 python3-pip libusb-1.0-0-dev \
  && apt install -y wget \ 
  && apt install -y adb \ 
  && apt install -y sqlite3 \
  && DEBIAN_FRONTEND=noninteractive apt-get -y install default-jre-headless
