### ISSUE TITLE
[iOS] mvt-ios check-iocs returns "Error: Missing argument 'FOLDER'."

### ISSUE THREAD

**Issue by PappaBu** [mvt-project/mvt#14]
Hi,

`mvt-ios check-backup --output /Users/user/Desktop/mvt_out /Users/user/Library/Application\ Support/MobileSync/Backup/<udid>`

creates files in `/Users/user/Desktop/mvt_out`
```
chrome_favicon.json
chrome_history.json
contacts.json
datausage.json
id_status_cache.json
manifest.json
sms_attachments.json
sms.json
timeline.csv
whatsapp.json
```

`mvt-ios check-iocs --iocs /Users/user/Desktop/mvt_out` returns an error:
```
Usage: mvt-ios check-iocs [OPTIONS] FOLDER
Try 'mvt-ios check-iocs --help' for help.

Error: Missing argument 'FOLDER'.
```

`mvt-ios check-iocs --help` :

```
Usage: mvt-ios check-iocs [OPTIONS] FOLDER

  Compare stored JSON results to provided indicators

Options:
  -i, --iocs PATH     Path to indicators file  [required]
  -l, --list-modules  Print list of available modules and exit
  -m, --module TEXT   Name of a single module you would like to run instead of
                      all
  --help              Show this message and exit.

```

What am I doing wrong?

**Comment by Te-k** [comment]
Hi,

The `check-iocs` requires you to provide the path of the IOC STIX file, like `mvt-ios check-iocs --iocs /path/to/stix/file /Users/user/Desktop/mvt_out`

**Comment by PappaBu** [comment]
> The `check-iocs` requires you to provide the path of the IOC STIX file, like `mvt-ios check-iocs --iocs /path/to/stix/file /Users/user/Desktop/mvt_out`

Thanks, it works:
`mvt-ios check-iocs --iocs /Users/user/Desktop/mvt_stix/pegasus.stix2 /Users/user/Desktop/mvt_out`

Error on first launch:
```
File "/usr/local/lib/python3.9/site-packages/mvt/ios/cli.py", line 175, in check_iocs
    for entry in BACKUP_MODULES + FS_MODULES + SYSDIAGNOSE_MODULES:
NameError: name 'SYSDIAGNOSE_MODULES' is not defined
```
After the fix line 175
`for entry in BACKUP_MODULES + FS_MODULES + SYSDIAGNOSE_MODULES:`
to
`for entry in BACKUP_MODULES + FS_MODULES:`
everything works as expected.

**Comment by Te-k** [comment]
Cool
