### ISSUE TITLE
ADB.EXE not present. Documentation should instruct on install of Android-SDK.

### ISSUE THREAD

**Issue by sunnyjamshedji** [mvt-project/mvt#146]
I'm a Windows user and not familiar with Android, Linux, Docker, etc., so was not sure where the ADB command comes from. I believe, I followed all the instructions to install Python, Git, Docker, WSL, Ubuntu LST, etc. After much frustration, found that it is from the Android SDK. Not sure if I missed the instruction to install it, but am unable to find this in the Documents. I think, it should be added.

Maybe, you can add this:
Install Android Platform Tools for ADB.EXE from https://developer.android.com/studio/releases/platform-tools
Extract ZIP to any folder and add it to your PATH variable, so it can be used from any prompt.

I am able to access and check the APKs, but not beyond that. Also, the problem about 'su' and non-rooted phones.
One issue is that the [damn] Moto 7 (Latest Android v10) keeps prompting to allow access for the computer and it never sticks. RSA key is the same each time.  Tried all sorts of solutions including Windows drivers and deleting adb key files in C:\Users\SunnyJ\.android. No luck. Getting it over to the device without rooting it was fruitless.

These instructions are also quite good, especially for checking the APKs.
https://itabcode.net/threads/how-to-check-remove-pegasus-spyware-from-mobile-phone-total-guide.564/

**Comment by Te-k** [comment]
So far the documentation does not include installation instructions for Windows. It would be good to add some once mvt will be stable enough on Windows.

**Comment by botherder** [comment]
Added instructions on platform tools. Windows is not currently supported, but added note it is preferable to run on WSL for now.
