### ISSUE TITLE
The InteractionC module database seems to be corrupted and recovery failed install sqlite3

### ISSUE THREAD

**Issue by TodayHorizon** [mvt-project/mvt#149]
I am receiving those 2 errors when I try to decrybt the backup everything is okey except few error messages like below; 

 [mvt.ios.modules.fs.webkit_resource_load_statistics] Database at path C:\Users\....\Documents\...\...\91\backup is malformed. Trying to recover...
 [mvt.ios.modules.fs.webkit_resource_load_statistics] The WebkitResourceLoadStatistics module database seems to be corrupted and recovery failed: Unable to recover without sqlite3 binary. Please install sqlite3!

 [mvt.ios.modules.fs.interactionc] The InteractionC module database seems to be corrupted and recovery failed: Unable to recover without sqlite3 binary. Please install sqlite3!

**Comment by dkg** [comment]
This message suggests that you need to `apt install sqlite3` (if you're on a debian-derived GNU/Linux system)

**Comment by TodayHorizon** [comment]
I am in windows, the sqlite3 is installed in python standard library, I tried also to install it manually but it is not resolving this problem.

**Comment by botherder** [comment]
The error indicates you don't have a `sqlite3` binary in your $PATH, it doesn't refer to the Python sqlite3 library.
Unfortunately Windows is not currently officially supported, and I would suggest you run MVT from WSL.
