### ISSUE TITLE
keygen i have this error

### ISSUE THREAD

**Issue by hamhicham** [mvt-project/mvt#152]
File "c:\users\pc\appdata\local\programs\python\python39\lib\site-packages\adb_shell\auth\keygen.py", line 248, in keygen
    with open(filepath, 'wb') as private_key_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\pc/.android/adbkey'

**Comment by botherder** [comment]
I am sorry but we do not currently support running natively on Windows. You can try with WSL.
https://docs.mvt.re/en/latest/install.html#mvt-on-windows
You also need to have Android tools properly installed and working.
