### ISSUE TITLE
[HELP] Possible signs of infection on iPhone of high-risk individual, next steps?

### ISSUE THREAD

**Issue by gregzo** [mvt-project/mvt#159]
We have found possible signs of infection in a high-risk individual's iPhone.

**Module:** Data Usage
**Events:** 4 instances of manipulated entries in 2016 and 2017

The individual was politically active during those years, member of parliament and member of an anti-corruption group in a sensitive country.

The individual is of course interested in getting to the bottom of this. Could you please offer some advice as to the next steps for him to take?

**Comment by botherder** [comment]
I'm sorry, this repository is only intended for bug reporting and development work, so I'm closing this ticket. Generally speaking though only the presence of manipulated entries does not necessarily automatically imply a compromise. That should only be considered an anomaly and as such it can be malicious or innocuous.
