### ISSUE TITLE
[Documentation] Add information about possible actions following a positive or ambiguous scan

### ISSUE THREAD

**Issue by gregzo** [mvt-project/mvt#161]
The documentation currently does not contain any information about handling a positive or ambiguous scan. I understand this may be outside of the current scope of this particular repository, but it would be very useful to include at least a link to another resource which may help high-risk individuals take action to get their devices analysed further.

**Comment by botherder** [comment]
I suppose the essential issue here is who is the audience for the tool and its documentation. My perspective is that this should not be a tool to be run by end-users for their own self-assessment, but by technologists equipped with the technical know-how to properly interpret the results as well as suggest any remediation plan to the person they are assisting.

**Comment by gregzo** [comment]
I understand. In that case, perhaps the documentation could be updated accordingly? [The Welcome section](https://docs.mvt.re/en/latest/index.html) contains the following language (emphasis mine):

> In this documentation you will find instructions on how to install and run the mvt-ios and mvt-android commands, **and guidance on how to interpret the extracted results.**

This contradicts the intended scope of the tool, and refers to a section of the documentation which seemingly was never written.

**Comment by botherder** [comment]
The documentation is under work (there's a starting point here https://docs.mvt.re/en/latest/ios/records.html), but that sentence I don't think quite contradicts the intended audience for the tool. Ultimately the guidance the documentation can provide is still targeted at a technical audience.

**Comment by gregzo** [comment]
Understood. I've submitted a PR to add a couple details about availability to that page.
