### ISSUE TITLE
NameError: name 'SYSDIAGNOSE_MODULES' is not defined

### ISSUE THREAD

**Issue by bucknet** [mvt-project/mvt#17]
Getting this error trying to use stix file from Amnesty, what am I doing wrong. 

mvt-ios check-iocs --iocs /mnt/c/Users/bucks/Desktop/MVT/pegasus.stix2 /mnt/c/Users/bucks/Desktop/MVT/output

1st arg location of stix file
2nd arg directory for output

ITunes output JSON files all in /mnt/c/Users/bucks/Desktop/MVT

**Comment by tyler-ground** [comment]
It's because of this line https://github.com/mvt-project/mvt/blob/ce9ee09c2d3f3c8e6d2ea426df5bfbdf073fb662/mvt/ios/cli.py#L175

They didn't define SYSDIAGNOSE_MODULES.

**Comment by recurrence** [comment]
It's because of this line https://github.com/mvt-project/mvt/blob/ce9ee09c2d3f3c8e6d2ea426df5bfbdf073fb662/mvt/ios/cli.py#L175

They didn't define SYSDIAGNOSE_MODULES

**Comment by bucknet** [comment]
Thanks, took that out and it worked.

**Comment by recurrence** [comment]
Well, this should still be fixed.  Not clear why this was closed :)

**Comment by recurrence** [comment]
I pushed a fix at #31
