### ISSUE TITLE
libimobiledevice-glue-1.0 not found when building Docker image

### ISSUE THREAD

**Issue by l0s** [mvt-project/mvt#182]
When building the Docker image according to [the instructions](https://docs.mvt.re/en/latest/docker.html), it fails with the following error:

    #6 35.57 checking for libplist... yes
    #6 35.58 checking for limd_glue... no
    #6 35.59 configure: error: Package requirements (libimobiledevice-glue-1.0 >= 1.0.0) were not met:
    #6 35.59 
    #6 35.59 No package 'libimobiledevice-glue-1.0' found
    #6 35.59 
    #6 35.59 Consider adjusting the PKG_CONFIG_PATH environment variable if you
    #6 35.59 installed software in a non-standard prefix.
    #6 35.59 
    #6 35.59 Alternatively, you may set the environment variables limd_glue_CFLAGS
    #6 35.59 and limd_glue_LIBS to avoid the need to call pkg-config.
    #6 35.59 See the pkg-config man page for more details.
    ------
    executor failed running [/bin/sh -c git clone https://github.com/libimobiledevice/libplist   && git clone https://github.com/libimobiledevice/libusbmuxd   && git clone https://github.com/libimobiledevice/libimobiledevice   && git clone https://github.com/libimobiledevice/usbmuxd   && cd libplist && ./autogen.sh && make && make install && ldconfig   && cd ../libusbmuxd && PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./autogen.sh && make && make install && ldconfig   && cd ../libimobiledevice && PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./autogen.sh --enable-debug && make && make install && ldconfig   && cd ../usbmuxd && PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./autogen.sh --prefix=/usr --sysconfdir=/etc --localstatedir=/var --runstatedir=/run && make && make install   && cd .. && rm -rf libplist libusbmuxd libimobiledevice usbmuxd]: exit code: 1

The command used to build is `docker build -t mvt .`. This was built using: `Docker version 20.10.8, build 3967b7d`.

**Comment by paulopacitti** [comment]
I'm having this issue too 😕
