### ISSUE TITLE
Confusion at  'path to backup' in SMS module

### ISSUE THREAD

**Issue by Michelle-coder** [mvt-project/mvt#190]
I was trying to check whether an android device is infected by Pegasus with my Mac. When typing `mvt-android check-backup --output /path/to/results/ /path/to/backup/` as mentioned [here](https://docs.mvt.re/en/latest/android/backup.html), there has been a misunderstanding since I thought '/apps' at the end of the path is needed too, so in the end I had a path like `./android-backup/apps/apps/com.android.providers.telephony/d_f `  This took me quite much time to find out because I only only got the error message 'Unable to find the SMS backup folder' and not the actual backup  path mvt tried to find. So I took a look in the source code, and '/apps' is already hard coded:

In sms.py
`... 
app_folder = os.path.join(self.base_folder,
                                  "apps",
                                  "com.android.providers.telephony",
                                  "d_f")
        if not os.path.exists(app_folder):
            raise FileNotFoundError("Unable to find the SMS backup folder")
...`

Maybe one can improve usability by checking the user input for containing '/apps' or by giving a hint in the error message that one does not need to write '/apps'.

**Comment by cmd-ctrl-freq** [comment]
This really tripped me up to. Luckily I found this issue.

**Comment by Te-k** [comment]
We have made some changes in that command, it now accepts the .ab file directly, but I have also clarified the documentation : https://docs.mvt.re/en/latest/android/backup/

Could you have a look and let me know if you think it is now more clear?
