### ISSUE TITLE
Problem using WSL...pls help

### ISSUE THREAD

**Issue by Capt-Oblivious** [mvt-project/mvt#192]
I've tried everything to get the command line to run under WSL Ubuntu to "check a Backup with mvt-ios" but it keeps coming back with: mvt-ios:  command not found

I'm typing the following:  mvt-ios decrypt-backup /mnt/c/**the path where I want to output**  /mnt/c/**the path where the encrypted backup is**

Can someone assist me...thanks

**Comment by botherder** [comment]
Are you sure you added the Python binary folder to PATH as indicated [here](https://docs.mvt.re/en/latest/install/)? It doesn't seem like it. Please check your setup. Closing this for now.
