### ISSUE TITLE
Url variable looks like it has a typo in virustotal.py

### ISSUE THREAD

**Issue by cafeTechne** [mvt-project/mvt#2]
url = f"https://www.virustotal.com/partners/sysinternals/file-reports?apikey={apikey}"
Is that f supposed to be there before the open quote for that string?

**Comment by nagesh-c** [comment]
I think it is PEP 498 style of formatting strings[1].

[1] https://realpython.com/python-f-strings/

**Comment by cafeTechne** [comment]
Sorry, I was unaware of this feature from python 3.6.
