### ISSUE TITLE
How does mvt handle different versions of sqlite db?

### ISSUE THREAD

**Issue by itinerant-fox** [mvt-project/mvt#212]
I ran mvt-ios on a iPhone 8 Plus 12.1.1 backup and got the following error:

 ERROR    [mvt.ios.modules.mixed.tcc] Error in running extraction from module TCC: no such column: auth_value
                  Traceback (most recent call last):
                    File "████████/mvt/mvt/common/module.py", line 152, in run_module
                      module.run()
                    File "████████/mvt/mvt/ios/modules/mixed/tcc.py", line 88, in run
                      self.process_db(self.file_path)
                    File "████████/mvt/mvt/ios/modules/mixed/tcc.py", line 53, in process_db
                      cur.execute("""SELECT
                  sqlite3.OperationalError: no such column: auth_value

I checked the APOLLO project @ https://github.com/mac4n6/APOLLO/blob/master/modules/tcc_db.txt to see how it is decoded and saw that query changed starting from iOS 14. Does mvt have a plan to handle older versions?

**Comment by botherder** [comment]
Can  you provide the schema for the table you have?

**Comment by itinerant-fox** [comment]
CREATE TABLE IF NOT EXISTS "access" (    
     service        TEXT        NOT NULL,
     client         TEXT        NOT NULL,
     client_type    INTEGER     NOT NULL,
     allowed        INTEGER     NOT NULL,
     prompt_count   INTEGER     NOT NULL,
     csreq          BLOB,
     policy_id      INTEGER,
     indirect_object_identifier_type    INTEGER,
     indirect_object_identifier         TEXT DEFAULT 'UNUSED',
     indirect_object_code_identity      BLOB,
     flags          INTEGER,
     last_modified  INTEGER     NOT NULL DEFAULT (CAST(strftime('%s','now') AS INTEGER)
),     PRIMARY KEY (service, client, client_type, indirect_object_identifier),
    FOREIGN KEY (policy_id) REFERENCES policies(id) ON DELETE CASCADE ON UPDATE CASCADE);

**Comment by Te-k** [comment]
Hi, I just pushed a fix for that issue, could you test with the last commit?

**Comment by Te-k** [comment]
Closing that issue, let me know if you still have this problem

**Comment by itinerant-fox** [comment]
Sorry for the late reply. 
Tested with the latest commit. It works fine. Thanks
