### ISSUE TITLE
The path you specified is a not a folder!

### ISSUE THREAD

**Issue by MikeResearcher** [mvt-project/mvt#214]
All,

I'm on a Mac OS and a Kali Linux machines with the latest updates.  I have been testing an Android 12 Pixel phone.  I'm able to execute all other commands with mvt-android.  Although, when I run this command,  I receive the following error on both my Linux and Mac OS machines.  I'm I missing something?

mvt-android check-backup --output Desktop/results Desktop/apps/com.android.providers.telephony/d_f/000002_sms_backup --iocs Desktop/stalkerware.stix2.txt
MVT - Mobile Verification Toolkit
                https://mvt.re
                Version: 1.2.14

12:00:27 INFO     [mvt.android.cli] Checking ADB backup located at:                                                     
                  Desktop/apps/com.android.providers.telephony/d_f/000002_sms_backup                                    
         INFO     [mvt.android.cli] Parsing STIX2 indicators file at path Desktop/stalkerware.stix2.txt                 
         INFO     [mvt.android.cli] Loaded a total of 2300 indicators                                                   
         CRITICAL [mvt.android.cli] The path you specified is a not a folder!

**Comment by botherder** [comment]
You should provide the path to the root of the backup, rather than the specific sms backup file.

**Comment by MikeResearcher** [comment]
Thanks.  I see what I was doing incorrectly.
