### ISSUE TITLE
Truncated configuration_profiles.json (iOS)

### ISSUE THREAD

**Issue by chatchavan** [mvt-project/mvt#218]
The command `mvt-ios check-backup` yielded the following error:

```
         ERROR    [mvt.ios.modules.backup.configuration_profiles] Unable to store results of module                   
                  ConfigurationProfiles to file configuration_profiles.json: 'utf-8' codec can't decode byte 0xf8 in  
                  position 0: invalid start byte 
```

The last lines of the file `configuration_profiles.json` is the following:

```
        "relative_path": "Library/ConfigurationProfiles/MDMEvents.plist",
        "domain": "SysSharedContainerDomain-systemgroup.com.apple.configurationprofiles",
        "plist": {
            "PushTokenDataSentToServerKey": 
```

## Further info
* MVT 1.2.14, BackupInfo build Version: 19B81 
* Device backup: iPhone 12 mini, iOS 15.1.1
* Ran on macOS (Apple Silicon chip)

**Comment by Te-k** [comment]
Hi, Thanks for reporting this bug. Do you think you could share the configuration file with us?

**Comment by chatchavan** [comment]
[configuration_profiles.json.zip](https://github.com/mvt-project/mvt/files/7653317/configuration_profiles.json.zip)

**Comment by Te-k** [comment]
Thanks, could you share the file 70/70b516f61cac24ea1037e8431f13b3029d3ac76a? (if you prefer to share privately, please send it to tek AT randhome.io )

**Comment by chatchavan** [comment]
Sent to your email.

**Comment by Te-k** [comment]
I cannot manage to reproduce this issue, but I realise there has been some changes with this module recently, could you try to see if you still encounter this issue with the last commit?

**Comment by chatchavan** [comment]
Just tested today (08 Dec. 21) with the latest version from Github. This problem is solved!
