### ISSUE TITLE
[Ubuntu] LIBUSB_ERROR_TIMEOUT [-7] error message

### ISSUE THREAD

**Issue by repsorp** [mvt-project/mvt#22]
`mvt-android download-apks --output /path/to/folder` returns a CRITICAL error message:

```
CRITICAL [mvt.android.modules.adb.base] Could not receive data from    
                  first ########## (timeout 5000ms): LIBUSB_ERROR_TIMEOUT [-7]  
```
same error message with `mvt-android check-adb
` command

Ubuntu 20.10

**Comment by goshawk22** [comment]
What happens if you run adb devices?

**Comment by repsorp** [comment]
mvt-android just woking fine with another rooted mobile
Does the mobile have to be rooted for mtv-android to work?

**Comment by guillaumemarion** [comment]
I had the same problem but "adb devices" told me that my device was unauthorized.

The following steps worked for me. As your phone doesn't appears to be unauthorized, it may not help you :

1. mvt command leaded to the same error you got  

`mvt-android download-apks --output /path/to/folder `

CRITICAL [mvt.android.modules.adb.base] Could not receive data from    
                  first ########## (timeout 5000ms): LIBUSB_ERROR_TIMEOUT [-7]  

2. Revoke USB Debugging on phone

Go to the developer options on the phone and click "Revoke USB debugging authorization" 

3. Start ADB Server:

```
adb start-server
```
4. Unplug / Replug the device

The device will ask if you are agree to connect the computer id. You need to confirm it.

5. Now Check the device

`adb device`

The phone appeared as authorized

5. Kill ADB Server:

```
adb kill-server
```

6. Try again :

```
mvt-android download-apks --output /path/to/folder
```
No more `LIBUSB_ERROR_TIMEOUT [-7]` on my side

**Comment by repsorp** [comment]
It's working now on both  rooted and not rooted mobiles
Had to run an adb kill-server command in order to make it work

**Comment by goshawk22** [comment]
@guillaumemarion same here, was just going to see if the device was authorized.

**Comment by momchilov** [comment]
@guillaumemarion thanks for the suggestion. It's still not working for me on an unrooted OnePlus 6 phone.

**Comment by victor95pc** [comment]
Getting a lot of `The Android device does not seem to have a `su` binary. Cannot run this module.`, prob need to get the phone rooted to make it work 100%

**Comment by juliusHin** [comment]
> I had the same problem but "adb devices" told me that my device was unauthorized.
> 
> The following steps worked for me. As your phone doesn't appears to be unauthorized, it may not help you :
> 
> 1. mvt command leaded to the same error you got
> 
> `mvt-android download-apks --output /path/to/folder `
> 
> CRITICAL [mvt.android.modules.adb.base] Could not receive data from
> first ########## (timeout 5000ms): LIBUSB_ERROR_TIMEOUT [-7]
> 
> 1. Revoke USB Debugging on phone
> 
> Go to the developer options on the phone and click "Revoke USB debugging authorization"
> 
> 1. Start ADB Server:
> 
> ```
> adb start-server
> ```
> 
> 1. Unplug / Replug the device
> 
> The device will ask if you are agree to connect the computer id. You need to confirm it.
> 
> 1. Now Check the device
> 
> `adb device`
> 
> The phone appeared as authorized
> 
> 1. Kill ADB Server:
> 
> ```
> adb kill-server
> ```
> 
> 1. Try again :
> 
> ```
> mvt-android download-apks --output /path/to/folder
> ```
> 
> No more `LIBUSB_ERROR_TIMEOUT [-7]` on my side

awesome! it worked!

**Comment by williamxlr** [comment]
Great step by step awesome!
