### ISSUE TITLE
check-backup fails with "The path you specified is a not a folder!"

### ISSUE THREAD

**Issue by gpawelczak** [mvt-project/mvt#224]
mvt-android check-backup -o tmp/mvt backup.tar
fails with 
CRITICAL [mvt.android.cli] The path you specified is a not a folder!

The folder is there
$ ls -ld smsbackup/
drwxrwxr-x 2 gp gp 4096 gru 21 19:37 smsbackup/

The same error occurs when a non-existent folder is specified in the option argument.
mvt version: 1.4.0

**Comment by Te-k** [comment]
The right syntax for `check-backup` is `mvt-android check-backup --output /path/to/results/ /path/to/backup/`, you need to extract the tar folder first, check the [documentation](https://docs.mvt.re/en/latest/android/backup/) for more information
