### ISSUE TITLE
Both cytrox.stix2 and stalkerware.stix2 parsing fails

### ISSUE THREAD

**Issue by gpawelczak** [mvt-project/mvt#225]
2 stix2 files mentioned in the documentation cannot be parsed:
         INFO     [mvt.android.cli] Parsing STIX2 indicators file at path ~/Downloads/cytrox.stix2                                                                                                                                                                            
         CRITICAL [mvt.android.cli] Unable to parse STIX2 indicators file, the file seems malformed or in the wrong format

Only pegasus.stix2 file can be parsed:

         INFO     [mvt.android.cli] Parsing STIX2 indicators file at path ~/Downloads/pegasus.stix2                                                                                                                                                                           
         INFO     [mvt.android.cli] Loaded a total of 1499 indicators

**Comment by Te-k** [comment]
It works on my machine:
```
         INFO     [mvt.ios.cli] Parsing STIX2 indicators file at  path cytrox.stix2                               
         INFO     [mvt.ios.cli] Loaded a total of 330 indicators 
```

What mvt version do you have? What Cytrox.stix2 version do you have?

**Comment by gpawelczak** [comment]
mvt version: 1.4.0
Cytrox: https://github.com/AmnestyTech/investigations/tree/master/2021-12-16_cytrox/cytrox.stix2

**Comment by Te-k** [comment]
Can you try with the last commit? (`git clone https://github.com/mvt-project/mvt.git`then `cd mvt` and `pip install .`)

**Comment by gpawelczak** [comment]
Still fails:
mvt-android check-adb -i ~/Downloads/cytrox.stix2 -o mvt


        MVT - Mobile Verification Toolkit
                https://mvt.re
                Version: 1.4.0


14:14:17 INFO     [mvt.android.cli] Checking Android through adb bridge                                                                                                                                                                                                                  
         INFO     [mvt.android.cli] Parsing STIX2 indicators file at path /home/gp/Downloads/cytrox.stix2                                                                                                                                                                            
         CRITICAL [mvt.android.cli] Unable to parse STIX2 indicators file, the file seems malformed or in the wrong format

**Comment by Te-k** [comment]
Hmm, I don't understand what is happening here. Could you share the hash of both STIX files?

**Comment by gpawelczak** [comment]
26bac89c9bf73eeadd6acda493d65dcb2b6caac8d112064f4d3766a5c08ea6cccbd5d47c07a84bf8a17a078fd4cf3becaca22553263bf8cff75c3d0f3fc69a1e  cytrox.stix2
3c905feb8d8a138fe80274c946d3028df8246b56e5f2939c5af538aefefd23b5d5341cd22e8c07e93d441a2ef23c851c3965acefbedc48c7cc835b09819eef11  pegasus.stix2
bbbd588feb434cba52682ef398d5a69d5e0a4d4fed112d96712503b06d8b697fd46d52eb646dc81340a2f4f1b12aaee0d65edc70bfe5b4043533feb85af586ef  stalkerware.stix2

**Comment by gpawelczak** [comment]
Not sure this is relevant, but pegasus.stix2 is JSON and the other two seem to be HTML

**Comment by gpawelczak** [comment]
OK, looks like pegasus.stix2 link on the doc page leads to json directly, but the other  two to github page ....

**Comment by Te-k** [comment]
Indeed they lead to the github page that allows to download the raw format. I'll fix the doc
