### ISSUE TITLE
Samsung Not supported 

### ISSUE THREAD

**Issue by rahimbtc** [mvt-project/mvt#232]
i'm testing the check-adb on my samsung phone on windows 10 but i got this error usb1.USBErrorNotSupported: LIBUSB_ERROR_NOT_SUPPORTED [-12]

**Comment by kpcyrd** [comment]
I think this could be a Windows issue instead of a Samsung issue, "[MVT does not currently officially support running natively on Windows](https://docs.mvt.re/en/latest/install/#mvt-on-windows)".

**Comment by rahimbtc** [comment]
Is there any docs describing how to use it properly or any DLLs needed for windows !?

**Comment by kpcyrd** [comment]
No, the docs I've linked suggest using the [Windows Subsystem Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/about) and following the Linux install instructions. :)

**Comment by Te-k** [comment]
Indeed, MVT is not supported on Windows, you can check the documentation [here](https://docs.mvt.re/en/latest/install/).
