### ISSUE TITLE
Unable to install the latest version => Could not find a version that satisfies the requirement iOSbackup>=0.9.921 (from mvt)

### ISSUE THREAD

**Issue by atu1973** [mvt-project/mvt#233]
Running into an issue installing the latest version.

**running the command :** 
```
j@jt:~$ pip3 install --no-cache-dir mvt

**The following is the output :**

Collecting mvt
  Downloading https://files.pythonhosted.org/packages/ce/08/1fee7825ebce930782b6d852fff8dd42d352acc69385880e55dcef234d33/mvt-1.4.1-py3-none-any.whl (290kB)
    100% |████████████████████████████████| 296kB 148kB/s 
Collecting click>=8.0.3 (from mvt)
  Downloading https://files.pythonhosted.org/packages/48/58/c8aa6a8e62cc75f39fee1092c45d6b6ba684122697d7ce7d53f64f98a129/click-8.0.3-py3-none-any.whl (97kB)
    100% |████████████████████████████████| 102kB 219kB/s 
Collecting packaging>=21.0 (from mvt)
  Downloading https://files.pythonhosted.org/packages/05/8e/8de486cbd03baba4deef4142bd643a3e7bbe954a784dc1bb17142572d127/packaging-21.3-py3-none-any.whl (40kB)
    100% |████████████████████████████████| 40kB 87kB/s 
Collecting requests>=2.26.0 (from mvt)
  Downloading https://files.pythonhosted.org/packages/2d/61/08076519c80041bc0ffa1a8af0cbd3bf3e2b62af10435d269a9d0f40564d/requests-2.27.1-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 71kB 147kB/s 
Collecting rich>=10.12.0 (from mvt)
  Downloading https://files.pythonhosted.org/packages/0a/0d/58939059015dce00122b008c3edccbb68f0767126020c939116e6d764cd7/rich-10.16.2-py3-none-any.whl (214kB)
    100% |████████████████████████████████| 215kB 310kB/s 
Collecting tld>=0.12.6 (from mvt)
  Downloading https://files.pythonhosted.org/packages/4e/07/d07d9c3ced44cbd8aa1974dae29801de40645c5281c994c93e60f7e076da/tld-0.12.6-py36-none-any.whl (412kB)
    100% |████████████████████████████████| 419kB 1.4MB/s 
Collecting tqdm>=4.62.3 (from mvt)
  Downloading https://files.pythonhosted.org/packages/63/f3/b7a1b8e40fd1bd049a34566eb353527bb9b8e9b98f8b6cf803bb64d8ce95/tqdm-4.62.3-py2.py3-none-any.whl (76kB)
    100% |████████████████████████████████| 81kB 171kB/s 
Collecting iOSbackup>=0.9.921 (from mvt)
  Could not find a version that satisfies the requirement iOSbackup>=0.9.921 (from mvt) (from versions: 0.9.0, 0.9.1, 0.9.2, 0.9.9, 0.9.901, 0.9.902, 0.9.903, 0.9.904, 0.9.910, 0.9.912, 0.9.913)
No matching distribution found for iOSbackup>=0.9.921 (from mvt)
```

**Comment by Te-k** [comment]
I am not sure what is the issue there, there is a version 0.9.921 of iOSbackup on [pypi](https://pypi.org/project/iOSbackup/)

**Comment by PseudoFIame** [comment]
Same issue here. I am able to install iOSbackup directly, however even afterwards pip3 refuses to install due to unsatisfying requirements of iOSbackup.
I am puzzled here. Any idea?

PS: Simply installing iOSbackup installed on my testing OS (debian 10/buster) version 0.9.913, which is too old to match the requirement. There is indeed no newer version available. Other linux OSes like Ubuntu 20.04 work out of the box.

**Comment by botherder** [comment]
Unfortunately it's because iOSbackup is marked to require Python 3.8:
https://pypi.org/project/iOSbackup/
You are probably using Python 3.7.

**Comment by Manamama** [comment]
Copying myself from related https://github.com/mvt-project/mvt/issues/230 
I ran into similar problems, as the older version worked in my configuration (Linux, Python 3.6). 
After trying compiling it by hand to enforce the newest version and then debugging and tinkering with the resulting issues with  iOSbackup>=0.9.921, the only fix was to upgrade Python3 itself to 3.9. 
It then allowed me the regular installation via:
pip3 install --upgrade mvt 


NB. Careful with this Python 3.9, as it breaks default Terminal in Ubuntu (which still requires Python 3.6), so a fix is needed: 
https://www.maketecheasier.com/fix-ubuntu-cannot-open-terminal/
https://askubuntu.com/questions/1132349/terminal-not-opening-up-after-upgrading-python-to-3-7
(or installing Terminator - its alternative).

**Comment by botherder** [comment]
I have opened a ticket with the developer of iOSbackup, who asked if anyone could test whether the latest version works just as fine with Python 3.7. If anyone has time to test this (I do not at the moment), it would be helpful to report:
https://github.com/avibrazil/iOSbackup/issues/19

If indeed iOSbackup 0.9.921 works just fine with Python 3.7, we could kindly ask the developer to change the setup.py so that this installation problem is resolved.

**Comment by avibrazil** [comment]
I’m the developer of iOSbackup.
I can't remember anymore why I put Python 3.8 as a restriction.
Please someone force an installation on older Python and let me know if it works, then I'll reduce the version requirement.

**Comment by Manamama** [comment]
I have tested it and it seems to work. Steps to reproduce (and test for yourself):

1. Install both python3.6 and python3.9

2. Install the _update-alternatives_ package to switch between the two, add the python alternatives to the list, etc. (I am skipping this part, see any guide to update-alternatives)

3. Set python3.6 as active via: 
`sudo update-alternatives --config python`

A. With Python3.6 as active, the standard 
`pip3 install mvt` 
still often results in:
      _MVT - Mobile Verification Toolkit
                https://mvt.re
                Version: 1.2.11
                Version 1.5.3 is available! Upgrade mvt!_

(even with my pip3 still showing: 
`pip3 -V`
_pip 22.0.4 from /home/[username]/.local/lib/python3.9/site-packages/pip (python 3.9)_
for some strange reason. )

B. This trick however works:
`pip3 install **--ignore-installed**  mvt`
or, to be doubly sure:
` python3.9 -m pip install pip install --ignore-installed  mvt`

It updates mvt:

`mvt-android version`

        _MVT - Mobile Verification Toolkit
                https://mvt.re
                Version: 1.5.3_

, which works even with python3.6 active:
`python3 -V`
_Python 3.6.9_


I hope the above makes some IT sense.

**Comment by Kirutian** [comment]
Same issue. Using 
pip3 --version
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)

**Comment by emrecio** [comment]
I don't need iOS, just the android version, is there a "skip" option?

**Comment by Te-k** [comment]
Some update on this issue : [iOSBackup](https://github.com/avibrazil/iOSbackup/issues/19) supports python 3.7+ for now, but it relies on [avibrazil/NSKeyedUnArchiver](https://github.com/avibrazil/NSKeyedUnArchiver) which requires python 3.8+ in order to have UID tokens support in [plistlib](https://docs.python.org/3.12/library/plistlib.html).

So unless this changes in the future, MVT will require python 3.8+.
