### ISSUE TITLE
Download path missing in documentation of mvt-ios download-iocs

### ISSUE THREAD

**Issue by Dr-Big-Man** [mvt-project/mvt#237]
Documentation of command mvt-ios download-iocs explains that the command can be used to download latest public indicator files. 

Running command on macOS yields:
```
21:29:44 INFO     [mvt.ios.cli] Downloading indicator file 'NSO Group Pegasus Indicators of Compromise' from
                  'https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/pegasus.stix2'
         INFO     [mvt.ios.cli] Saved indicator file to 'raw.githubusercontent.com_AmnestyTech_investigations_master_2021-07-18_nso_pegasus.stix2'
         INFO     [mvt.ios.cli] Downloading indicator file 'Cytrox Predator Spyware Indicators of Compromise' from
                  'https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-12-16_cytrox/cytrox.stix2'
         INFO     [mvt.ios.cli] Saved indicator file to 'raw.githubusercontent.com_AmnestyTech_investigations_master_2021-12-16_cytrox_cytrox.stix2'
```

However, it is totally unclear where the downloaded files are stored. The locations given are not retrievable on macOS. 

Please add description of the path where the downloaded files are stored - many thanks in advance.

**Comment by botherder** [comment]
They are stored in an "mvt" appdir as per this documentation:
https://pypi.org/project/appdirs/

**Comment by Dr-Big-Man** [comment]
> They are stored in an "mvt" appdir as per this documentation: https://pypi.org/project/appdirs/

Many thanks for the very useful information - appreciated. Besides I can confirm, that the files had indeed been stored at `~/Library/Application\ Support/mvt` on my machine. IMHO I would consider it useful, if this information could be added to the documentation of mvt? I will have a look, if I can submit kind of a "pull request" for the documentation. Thanks again for immediate help.

**Comment by alisam1988** [comment]
در تاریخ ۱۹ ژانویهٔ ۲۰۲۲ ۲۲:۲۸، "Dr. Big Man - aka dBm" ***@***.***> نوشت:

They are stored in an "mvt" appdir as per this documentation: https://pypi.org/project/appdirs/

Many thanks for the very useful information - appreciated. Besides I can confirm, that the files had indeed been stored at ~/Library/Application\ Support/mvt on my machine. IMHO I would consider it useful, if this information could be added to the documentation of mvt? I will have a look, if I can submit kind of a "pull request" for the documentation. Thanks again for immediate help.

**Comment by Te-k** [comment]
I have added this information in the documentation [there](https://docs.mvt.re/en/latest/iocs/). Let me know if you think more information should be included.
