### ISSUE TITLE
v1.4.5 not tagged

### ISSUE THREAD

**Issue by ickc** [mvt-project/mvt#238]
v1.4.5 is currently not tagged. Perhaps it should be git tagged first before releasing to PyPI to ensure that it is tagged, and the git tag will always match the commit that released to PyPI.

c.f.

- https://github.com/conda-forge/mvt-feedstock/pull/11#issuecomment-1017832784
- #199

**Comment by botherder** [comment]
Yes it should be. Fixing now.
