### ISSUE TITLE
Installing MVT and none is happening when commands run 

### ISSUE THREAD

**Issue by mamaoi** [mvt-project/mvt#248]
Hi
Tried mvt-android download-apks and result is :  
> 

    Extracted at total of 0 installed 
    Selected only 0 packages
    No packages were selected for  download

so,  none of the commands works, then tried to remove the installed packages and try to install it from source, but the result is :

> 

    rm /home/$USER/.local/bin/mvt-*
    sudo pip uninstall mvt
    pip uninstall mvt
    git clone https://github.com/mvt-project/mvt
    cd mvt
    sudo pip3 install .

> 

    Collecting appdirs>=1.4.4
    Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
    ERROR: Could not find a version that satisfies the requirement iOSbackup>=0.9.921 (from mvt) (from versions: 0.9.0, 0.9.1, 0.9.2, 0.9.9, 0.9.901, 0.9.902, 0.9.903, 0.9.904, 0.9.910, 0.9.912, 0.9.913)
    ERROR: No matching distribution found for `iOSbackup>=0.9.921

any help !! thanks

**Comment by m000lie** [comment]
May I know what your python version is?

**Comment by mamaoi** [comment]
I have installed, or attempted to install, with sudo pip3 install .
> 

    python --version
    Python 2.7.17

    python3 --version
    Python 3.6.9

**Comment by m000lie** [comment]
I think i know the issue. 
check out:
https://pypi.org/project/iOSbackup/0.9.913/
https://pypi.org/project/iOSbackup/0.9.921/

v0.9.913 requires python >=3.6 whereas v0.9.921 require python >= 3.8
I see in the error message that it only manages to find version 0.9.913 as latest version, you will need to update your python version to install mvt

**Comment by mamaoi** [comment]
thanks alot, I will, and wish you a really nice day

**Comment by m000lie** [comment]
No problem! Happy that I was able to help you, have a good day!
