### ISSUE TITLE
Error in running extraction from module Packages: HTTPSConnectionPool(host='api.koodous.com', port=443)

### ISSUE THREAD

**Issue by Sumarua** [mvt-project/mvt#255]
Error in running extraction from module Packages:   
                  HTTPSConnectionPool(host='api.koodous.com', port=443): Max retries exceeded with url:/apks/0c7bc50450e6cfbfbeea2aead9ba10a7bbb45f5c729cc460410e475f4708a85e (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa23fae5fa0>:     
 Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))                                                                          
                  
Traceback (most recent call last):                                                     
                    File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 174, in    
                  _new_conn                                                                              
                      conn = connection.create_connection(                                               
                    File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 72, in
                  create_connection                                                                      
                      for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):             
                    File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo                        
                      for res in _socket.getaddrinfo(host, port, family, type, proto, flags):            
                  socket.gaierror: [Errno -3] Temporary failure in name resolution                       
                                                                                                         
                  During handling of the above exception, another exception occurred:                    
                                                                                                         
                  Traceback (most recent call last):                                                     
                    File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in
                  urlopen                                                                                
                      httplib_response = self._make_request(                                             
                    File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 386, in
                  _make_request                                                                          
                      self._validate_conn(conn)                                                          
                    File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 1040,  
                  in _validate_conn                                                                      
                      conn.connect()                                                                     
                    File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 358, in    
                  connect                                                                                
                      conn = self._new_conn()                                                            
                    File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 186, in    
                  _new_conn                                                                              
                      raise NewConnectionError(                                                          
                  urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at   
                  0x7fa23fae5fa0>: Failed to establish a new connection: [Errno -3] Temporary failure in 
                  name resolution                                                                        
                                                                                                         
                  During handling of the above exception, another exception occurred:                    
                                                                                                         
                  Traceback (most recent call last):                                                     
                    File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 440, in send
                      resp = conn.urlopen(                                                               
                    File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 785, in
                  urlopen                                                                                
                      retries = retries.increment(                                                       
                    File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 592, in    
                  increment                                                                              
                      raise MaxRetryError(_pool, url, error or ResponseError(cause))                     
                  urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.koodous.com',          
                  port=443): Max retries exceeded with url:                                              
                  /apks/0c7bc50450e6cfbfbeea2aead9ba10a7bbb45f5c729cc460410e475f4708a85e (Caused by      
                  NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa23fae5fa0>:     
                  Failed to establish a new connection: [Errno -3] Temporary failure in name             
                  resolution'))                                                                          
                                                                                                         
                  During handling of the above exception, another exception occurred:                    
                                                                                                         
                  Traceback (most recent call last):                                                     
                    File "/usr/local/lib/python3.8/dist-packages/mvt/common/module.py", line 152, in     
                  run_module                                                                             
                      module.run()                                                                       
                    File "/usr/local/lib/python3.8/dist-packages/mvt/android/modules/adb/packages.py",   
                  line 243, in run                                                                       
                      koodous_lookup(packages_to_lookup)                                                 
                    File "/usr/local/lib/python3.8/dist-packages/mvt/android/lookups/koodous.py", line   
                  33, in koodous_lookup                                                                  
                      res = requests.get(url)                                                            
                    File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 75, in get       
                      return request('get', url, params=params, **kwargs)                                
                    File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 61, in request   
                      return session.request(method=method, url=url, **kwargs)                           
                    File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 529, in     
                  request                                                                                
                      resp = self.send(prep, **send_kwargs)                                              
                    File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 645, in send
                      r = adapter.send(request, **kwargs)                                                
                    File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 519, in send
                      raise ConnectionError(e, request=request)                                          
                  requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.koodous.com',       
                  port=443): Max retries exceeded with url:                                              
                  /apks/0c7bc50450e6cfbfbeea2aead9ba10a7bbb45f5c729cc460410e475f4708a85e (Caused by      
                  NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa23fae5fa0>:     
                  Failed to establish a new connection: [Errno -3] Temporary failure in name             
                  resolution'))                                                                          
         INFO     [mvt.android.modules.adb.logcat] Running module Logcat...                              
         INFO     [mvt.android.modules.adb.logcat] Current logcat logs stored at                         
                  /path/to/results/logcat.txt                                                            
         INFO     [mvt.android.modules.adb.logcat] Logcat logs prior to last reboot stored at            
                  /path/to/results/logcat_last.txt                                                       
         INFO     [mvt.android.modules.adb.logcat] The Logcat module does not support checking for       
                  indicators                                                                             
         INFO     [mvt.android.modules.adb.root_binaries] Running module RootBinaries...                 
09:08:06 INFO     [mvt.android.modules.adb.root_binaries] The RootBinaries module does not support       
                  checking for indicators                                                                
         INFO     [mvt.android.modules.adb.files] Running module Files...                                
         INFO     [mvt.android.modules.adb.files] Found 1383 files in primary Android data directories   
         INFO     [mvt.android.modules.adb.files] Processing full file listing. This may take a while... 
09:08:15 INFO     [mvt.android.modules.adb.files] Found 664213 total files

**Comment by Sumarua** [comment]
ERROR    [mvt.android.modules.adb.chrome_history] This module is optionally available in case   
                  the device is already rooted. Do NOT root your own device! 

ERROR    [mvt.android.modules.adb.whatsapp] This module is optionally available in case the     
                  device is already rooted. Do NOT root your own device!

 WARNING  [mvt.android.modules.adb.settings] Found suspicious setting "install_non_market_apps = 
                  1" (enabled installation of non-market apps) 

ERROR    [mvt.android.lookups.virustotal] Unfortunately VirusTotal lookup is disabled until     
                  further notice, due to unresolved issues with the API service.

**Comment by Sumarua** [comment]
This is the problem i had with wired connections.WIFI connection is normal.

**Comment by Te-k** [comment]
Yeah, it sounds like a network issue on your side, I close
