### ISSUE TITLE
Clarify data units in datausage records

### ISSUE THREAD

**Issue by besendorf** [mvt-project/mvt#256]
I just read some datausage records and was wondering what unit is used for wifi_in, wifi_out, wwan_in and wwan_out. I suspect its bytes, but it would be nice to clarify this somehow. Maybe directly in the json file but also in the documentation at:
https://docs.mvt.re/en/latest/ios/records/#datausagejson

**Comment by Te-k** [comment]
Indeed it is in bytes, I have updated the documentation, thanks.
