### ISSUE TITLE
zsh: command not found: mvt-ios

### ISSUE THREAD

**Issue by kylevass** [mvt-project/mvt#262]
I've followed documentation instructions on installing MVT for MacOS via Terminal

But when I go to run MVT, I'm getting the following error

"zsh: command not found: mvt-ios"

I've check to make sure all the dependencies are installed and that MVT installed properly. Not sure that it matters but I'm trying to run this on a new, silicon Mac (not Intel)

**Comment by botherder** [comment]
Have you added Python path to your $PATH in zshrc?
