### ISSUE TITLE
Last Processed Command samsung 

### ISSUE THREAD

**Issue by Troy1277** [mvt-project/mvt#277]
22:18:32.353 build-939-bundle-play
Device: samsung samsung SM-A025U1 a02que QC_Reference_Phone "qcom" a02q RP1A.200720.012.A025U1UES1BVD1 [armeabi-v7a, armeabi]

msm8953 is_snapdragon
samsung
FLAG_VARIANT_SAMSUNG_UHQA
is_snapdragon msm8953
2 changelist=22602870
USB can handle Hi-Res - sdk=30
OK flags=0x136708400000000
FLAG_VARIANT_SAMSUNG_UHQA
FLAG_SUPPORTS_USB
FLAG_NEEDS_EXTRA_SLEEPS
FLAG_SUPPORTS_SPEAKER
FLAG_OUT_PARAMS_UNDETECTABLE
FLAG_SUPPORTS_LDAC
FLAG_DLFCN
FLAG_ALLOW_DVC_EFFECT
FLAG_BT_DVC_EFFECT
 FLAG_STOP_FOR_PAUSE
INTERNAL_OUTPUT_FLAG_SR_384K 
INTERNAL_OUTPUT_FLAG_SR_352K
INTERNAL_OUTPUT_FLAG_SR_192K
INTERNAL_OUTPUT_FLAG_SR_176K
INTERNAL_OUTPUT_FLAG_SR_96K
INTERNAL_OUTPUT_FLAG_SR_88K

**Comment by Troy1277** [comment]
> 22:18:32.353 build-939-bundle-play
> Device: samsung samsung SM-A025U1 a02que QC_Reference_Phone "qcom" a02q RP1A.200720.012.A025U1UES1BVD1 [armeabi-v7a, armeabi]
> 
> msm8953 is_snapdragon
> samsung
> FLAG_VARIANT_SAMSUNG_UHQA
> is_snapdragon msm8953
> 2 changelist=22602870
> USB can handle Hi-Res - sdk=30
> OK flags=0x136708400000000
> FLAG_VARIANT_SAMSUNG_UHQA
> FLAG_SUPPORTS_USB
> FLAG_NEEDS_EXTRA_SLEEPS
> FLAG_SUPPORTS_SPEAKER
> FLAG_OUT_PARAMS_UNDETECTABLE
> FLAG_SUPPORTS_LDAC
> FLAG_DLFCN
> FLAG_ALLOW_DVC_EFFECT
> FLAG_BT_DVC_EFFECT
>  FLAG_STOP_FOR_PAUSE
> INTERNAL_OUTPUT_FLAG_SR_384K 
> INTERNAL_OUTPUT_FLAG_SR_352K
> INTERNAL_OUTPUT_FLAG_SR_192K
> INTERNAL_OUTPUT_FLAG_SR_176K
> INTERNAL_OUTPUT_FLAG_SR_96K
> INTERNAL_OUTPUT_FLAG_SR_88K
>

**Comment by Te-k** [comment]
Is there any question here ? Could you provide context ?
