### ISSUE TITLE
Interpret the reports

### ISSUE THREAD

**Issue by VMARTTARIN** [mvt-project/mvt#283]
Hi,

In which report/file can I find the detections of the apks? I have reviewed all the json created and I do not see it

Thanks
![Captura de pantalla 2022-06-21 125112](https://user-images.githubusercontent.com/106272527/174783127-7019baf2-89b6-4ecc-afaa-93a04c65daa3.png)

**Comment by Te-k** [comment]
Hi, what command did you use to generate that report?

**Comment by botherder** [comment]
@VMARTTARIN those are not stored. They are just looked up on VirusTotal. You should just look up the file on VT's website directly.

**Comment by botherder** [comment]
You can find that code in virustotal.py.
