### ISSUE TITLE
KeyError: 'description' with indicators.py

### ISSUE THREAD

**Issue by dsattali** [mvt-project/mvt#290]
Hi,

I get this error when running mvt-ios check-backup (after updating iocs) or mvt-ios check-iocs:

>     INFO     [mvt.ios.cli] Checking stored results against provided indicators...                                                                                                                      
>     INFO     [mvt.ios.cli] Parsing STIX2 indicators file at path /Users/XXX/Library/Application Support/mvt/raw.githubusercontent.com_mvt-project_mvt-indicators_main_2022-06-23_rcs_lab_rcs.stix2   
>     Traceback (most recent call last):
>       File "/opt/homebrew/bin/mvt-ios", line 8, in <module>
>         sys.exit(cli())
>       File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
>         return self.main(*args, **kwargs)
>       File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1055, in main
>         rv = self.invoke(ctx)
>       File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
>         return _process_result(sub_ctx.command.invoke(sub_ctx))
>       File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
>         return ctx.invoke(self.callback, **ctx.params)
>       File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 760, in invoke
>         return __callback(*args, **kwargs)
>       File "/opt/homebrew/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
>         return f(get_current_context(), *args, **kwargs)
>       File "/opt/homebrew/lib/python3.9/site-packages/mvt/ios/cli.py", line 277, in check_iocs
>         indicators.load_indicators_files(iocs)
>       File "/opt/homebrew/lib/python3.9/site-packages/mvt/common/indicators.py", line 187, in load_indicators_files
>         self.parse_stix2(file_path)
>       File "/opt/homebrew/lib/python3.9/site-packages/mvt/common/indicators.py", line 100, in parse_stix2
>         "description": entry["description"],
>     KeyError: 'description'

When I delete the line 100 of indicators.py, it works fine (but I don't know if I'm then missing some info...). Line 100 is: 

> 92        malware = {}
> 93        indicators = []
> 94        relationships = []
> 95        for entry in data.get("objects", []):
> 96            entry_type = entry.get("type", "")
> 97            if entry_type == "malware":
> 98                malware[entry["id"]] = {
> 99                    "name": entry["name"],
> 100                   "description": entry["description"],
> 101               }
> 102           elif entry_type == "indicator":
> 103               indicators.append(entry)
> 104           elif entry_type == "relationship":
> 105               relationships.append(entry)

I couldn't find any discussion about this issue.

Thanks for your help.

Best,

**Comment by botherder** [comment]
Thanks for reporting. This was already fixed in this commit https://github.com/mvt-project/mvt/commit/0d75dc3ba04bd0cbf5331d0741bc62aed7f6bde3.
