### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [mvt-project/mvt#294]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@nerrorsec) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by botherder** [comment]
Sure, thank you.

**Comment by botherder** [comment]
Added with f3e5763c6af35c6e7cfc2da0e7b6fee563546489.

**Comment by JamieSlome** [comment]
@botherder - thanks for your diligence 👍 

We will get more information sent over to you shortly, but just for reference, the report can be found here:
https://huntr.dev/bounties/f6bc31eb-7d02-4279-8a88-62306141295d/

It is private and only accessible to maintainers with repository write permissions :)
