### ISSUE TITLE
help with the tool.

### ISSUE THREAD

**Issue by carlosandradde22** [mvt-project/mvt#295]
I found 3 detection, but im not very expert with this tool, does it mean I have pegasus on my phone
![Screenshot_2022-08-16_18-38-47](https://user-images.githubusercontent.com/95318201/185003851-e94eb5c4-cd27-46aa-9951-7dc04657d2f5.png)
![Screenshot_2022-08-16_18-39-06](https://user-images.githubusercontent.com/95318201/185003853-46a7e284-ef89-4e5f-aed8-11fb60c85d31.png)
![Screenshot_2022-08-16_18-39-20](https://user-images.githubusercontent.com/95318201/185003855-b814cc16-8f95-43d9-95fc-a2f06da2368b.png)
?

**Comment by botherder** [comment]
No, it doesn't mean you have Pegasus on your phone. MVT is not a Pegasus detection tool, it's a forensic analysis tool. The results are only suggested some packages installed on the device are detected by some antivirus as suspicious on virustotal.com. You should check what those packages are and investigate further if you think they are not legitimate apps. For exampe, what is this WhatApp 5 Plus?

**Comment by carlosandradde22** [comment]
Thank you very much for your kind opinion, yes I ask because I'm not very familiarized with the tool, whatts app plus is another version of whatts app that I downloaded because it's personalizable. But the part where there are a lot of permissions are known apps as waze of Google talk

**Comment by botherder** [comment]
If you trust these apps, then it's up to you. Generally any custom third-party WhatsApp version sounds like a bad idea to me though.
