### ISSUE TITLE
advice: adb repo version in debian buster is too old for mvt

### ISSUE THREAD

**Issue by carlosm2** [mvt-project/mvt#3]
hi, this is not an issue, is an advice for user running debian buster, 

mvt was throwing me errors (on **Debian Buster**) that I couldn't debug, until I finally read that the `adb` error was due to the version, so I downloaded the latest version to successfully run the software 

actual adb version: 

```
Android Debug Bridge version 1.0.41
Version 31.0.2-7242960
```
thanks for this tool

**Comment by Zanthed** [comment]
It's not recommended to use Android development tools or toolkits from distro-specific repos as they are very outdated due to package freezing.

Arch Linux is the only known distro that seems to properly have up to date Android platform tools.

**Comment by alexmyczko** [comment]
that's why new packages get built into sid (or experimental), then move to testing, then after some freeze to stable.

maybe it's useful to someone
https://sid.ethz.ch/debian/mvt/

needs to have packaged what's in README (for proper packaging), or you can work them around using `pip3`

**Comment by rajasekharponakala** [comment]
I'm interested to work on this.

**Comment by Te-k** [comment]
So should we just update the documentation to install mvt?

**Comment by carlosm2** [comment]
> So should we just update the documentation to install mvt?

to make more accessible the documentation maybe, I can help if you need it

**Comment by botherder** [comment]
I updated the documentation to address this issue. It is preferable to install the platform tools from the official releases.
