### ISSUE TITLE
Install fails with pip3 on ubuntu

### ISSUE THREAD

**Issue by MultipleCrashes** [mvt-project/mvt#301]
installation issue on ubuntu 20.04
pip3 install mvt fails with below error meaasge

cannot find the version that satisfies requirement iOSbackup>.0.9.921 no matching distribution found

**Comment by deimidis** [comment]
I had the same problem in Manjaro, installed iOSbackup first (version 0.9.913), and then mvt install worked. But, it installed an old version, then I tried with Python 3.10, and worked without the iOSbackup problem and the current version. Maybe the part about python3.6 is outdated.

**Comment by kpcyrd** [comment]
@deimidis manjaro ships the mvt package from Arch Linux that you could just install, they ship an old version though.

**Comment by deimidis** [comment]
@kpcyrd thanks, I will try that later, for now installing with pip worked. Now I have to learn how to decode all the information :D

**Comment by botherder** [comment]
Because of [this issue](https://github.com/avibrazil/iOSbackup/issues/19) we have to enforce Python >= 3.8. If you have an older version, you need to upgrade I'm afraid.
