### ISSUE TITLE
i fall on error no device found for chrome history

### ISSUE THREAD

**Issue by Azaretdodo** [mvt-project/mvt#303]
hello,

`CRITICAL [mvt.android.modules.adb.chrome_history] No device found. Make
                  sure it is connected and unlocked.`

over the error as you see it isn't found by this error however i use brave for chrome this is only a shortcut for learn english using word reference thus why i happen this error for chrome ? too i want to understand with an example below : 

`INFO     [mvt.android.cmd_check_adb] Extracted 5 indicators for        
                  collection with name "TheNameOfTheThreat"`

over this information is dangerous or not ?

thanks you in advance for yours answer,

regards.

Azaretdodo.

**Comment by botherder** [comment]
The error means that it did not find any connected Android device. Please follow the documentation to see how to configure an Android device to be analyzed over USB. And no, that message is not dangerous, it's an "INFO" message informing how many indicators were collected for a provided indicators file. It is not a detection.
Please, try to refrain from opening too many GitHub Issues: these are being used for bug reporting. You should seek expert assistance if you wish to have your device checked.
