### ISSUE TITLE
Wrong folder for command on Android

### ISSUE THREAD

**Issue by iam0day** [mvt-project/mvt#32]
In the example shown on the [documentation](https://mvt.readthedocs.io/en/latest/android/backup.html) the destination folder is `sms` for the command `mvt-android check-backup --output sms .` but instead it should be `apps`, which consequently the correct command would be `mvt-android check-backup --output apps .`... Although you can always rename the folder if you want, in my opinion it is more appropriate to recommend the correct destination in the documentation.

As you can see after extracting my backup: 
![](https://user-images.githubusercontent.com/17969978/126404510-43286b51-83e5-4042-9b42-1b1d16b27604.jpeg)

**Comment by Te-k** [comment]
Indeed, it is `mvt-android check-backup --output OUTPUT_FOLDER SMS_FOLDER` so here `mvt-android check-backup --output . .`. 

I updated the doc accordingly, thanks
