### ISSUE TITLE
Question: What is ProtectedDomain in the iOS manifest.json file?

### ISSUE THREAD

**Issue by kushaldas** [mvt-project/mvt#33]
In the `manifest.json` file from iOS backup, contains values with domain as `ProtectedDomain`. Any tips on what are these domains/files? the `relativePath` value is empty in some of these.

**Comment by kushaldas** [comment]
I guess something to do with `tasks`. Any pointer will be helpful.

**Comment by botherder** [comment]
`manifest.json` contains records extracted from a backup's `Manifest.db` file, which indexes files backed up.
