### ISSUE TITLE
Update documentation to clarify that source is more recent than pypi

### ISSUE THREAD

**Issue by runasand** [mvt-project/mvt#331]
In some cases, bug fixes can take a few days or weeks to make their way into pypi. It would be great to see the documentation clarify that source is more recent than pypi. Perhaps also include instructions for uninstalling mvt-ios from pypi before installing from source.

**Comment by huyta55** [comment]
Hi, would this be a good issue for a first time contributor like me to work on? Could the issue be solved by me installing mvt-ios from PyPi first, then finding out how to remove it and then installong mvt-ios from source and then writing a How-To document on the entire process?

**Comment by Te-k** [comment]
Done with 1ad176788b52bdc8cdf097020721c0cc7c3ff2cd, thanks!
