### ISSUE TITLE
mvt.android.cmd_download_apks] Device is busy, maybe run `adb kill-server` and try again.

### ISSUE THREAD

**Issue by renozion** [mvt-project/mvt#343]
I'm stuck here friends, need to report apk to check with kaspersky but cannot download, any hints? Ive tried adb kill-server, reconnect kill it again, all that stuff and nothing seems to happen, always return the same stuff

**Comment by Te-k** [comment]
Can you connect with `adb shell`? If not it is probably a problem with your access to the phone than an MVT issue

**Comment by Te-k** [comment]
Ok, it doesn't sound like an MVT issue then, I close this issue.
