### ISSUE TITLE
com.apple.Numbers false warning

### ISSUE THREAD

**Issue by mc-17** [mvt-project/mvt#348]
When running against my phone, I see:

```
WARNING  [mvt.ios.modules.mixed.applications] Suspicious app not installed from the App Store or MDM: com.apple.Numbers
```

It was downloaded from the App Store though, and is the legit Apple one.

**Comment by Te-k** [comment]
Hi, could you share `applications_detected.json` file?

**Comment by Te-k** [comment]
I am closing, feel free to reopen if you have time to dig into this issue together
