### ISSUE TITLE
Check backup fails to produce output iOS 14 unencrypted backup

### ISSUE THREAD

**Issue by impartlogic** [mvt-project/mvt#35]
Ubuntu 20.04 Python 3.8.10
```
forensics@forensics-XPS-13-9365:~/mvt$ mvt-ios check-backup --output ~/Documents/iphone/output ~/Documents/iphone/00008020-001D54200101002E/
15:41:59 INFO     [mvt.ios.cli] Checking iTunes backup located at:             
                  /home/forensics/Documents/iphone/00008020-001D54200101002E/  
         INFO     [mvt.ios.modules.fs.safari_browserstate] Running module      
                  SafariBrowserState...                                        
         ERROR    [mvt.ios.modules.fs.safari_browserstate] There might be no   
                  data to extract by module SafariBrowserState: Unable to find 
                  the module's database file                                   
         INFO     [mvt.ios.modules.fs.safari_history] Running module           
                  SafariHistory...                                             
         ERROR    [mvt.ios.modules.fs.safari_history] There might be no data to
                  extract by module SafariHistory: Unable to find the module's 
                  database file                                                
         INFO     [mvt.ios.modules.fs.net_datausage] Running module            
                  Datausage...                                                 
         INFO     [mvt.ios.modules.fs.net_datausage] Found DataUsage database  
                  at path: /home/forensics/Documents/iphone/00008020-001D542001
                  01002E/0d/0d609c54856a9bb2d56729df1d68f2958a88426b           
         INFO     [mvt.ios.modules.fs.net_datausage] Extracted information on  
                  7133 processes                                               
15:42:00 INFO     [mvt.ios.modules.fs.sms] Running module SMS...               
         INFO     [mvt.ios.modules.fs.sms] Found SMS database at path: /home/fo
                  rensics/Documents/iphone/00008020-001D54200101002E/3d/3d0d7e5
                  fb2ce288813306e4d4636395e047a3d28                            
15:42:01 INFO     [mvt.ios.modules.fs.sms] Extracted a total of 745 SMS        
                  messages containing links                                    
         INFO     [mvt.ios.modules.fs.sms_attachments] Running module          
                  SMSAttachments...                                            
         INFO     [mvt.ios.modules.fs.sms_attachments] Found SMS database at   
                  path: /home/forensics/Documents/iphone/00008020-001D542001010
                  02E/3d/3d0d7e5fb2ce288813306e4d4636395e047a3d28              
         INFO     [mvt.ios.modules.fs.sms_attachments] Extracted a total of    
                  3483 SMS attachments                                         
         INFO     [mvt.ios.modules.fs.chrome_history] Running module           
                  ChromeHistory...                                             
         INFO     [mvt.ios.modules.fs.chrome_history] Found Chrome history     
                  database at path: /home/forensics/Documents/iphone/00008020-0
                  01D54200101002E/fa/faf971ce92c3ac508c018dce1bef2a8b8e9838f1  
         INFO     [mvt.ios.modules.fs.chrome_history] Extracted a total of 60  
                  history items                                                
         INFO     [mvt.ios.modules.fs.chrome_favicon] Running module           
                  ChromeFavicon...                                             
         INFO     [mvt.ios.modules.fs.chrome_favicon] Found Chrome favicon     
                  cache database at path: /home/forensics/Documents/iphone/0000
                  8020-001D54200101002E/55/55680ab883d0fdcffd94f959b1632e5fbbb1
                  8c5b                                                         
         INFO     [mvt.ios.modules.fs.chrome_favicon] Extracted a total of 42  
                  favicon records                                              
         INFO     [mvt.ios.modules.fs.webkit_session_resource_log] Running     
                  module WebkitSessionResourceLog...                           
Traceback (most recent call last):
  File "/home/forensics/.local/bin/mvt-ios", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/forensics/.local/lib/python3.8/site-packages/mvt/ios/cli.py", line 102, in check_backup
    run_module(m)
  File "/home/forensics/.local/lib/python3.8/site-packages/mvt/common/module.py", line 146, in run_module
    module.check_indicators()
  File "/home/forensics/.local/lib/python3.8/site-packages/mvt/ios/modules/fs/webkit_session_resource_log.py", line 84, in check_indicators
    if self.indicators.check_domains(all_origins):
AttributeError: 'NoneType' object has no attribute 'check_domains'
```

**Comment by s3edeh** [comment]
This also happens on other iOS versions, happened to me on iOS 12.5.4

**Comment by adpio** [comment]
Similar issue on python 3.9.6 and latest Big Sur 11.4

**Comment by kris71** [comment]
This issue also happens with a backup of ios 14.7 for me.

**Comment by kywazim** [comment]
> Ubuntu 20.04 Python 3.8.10
> 
> ```
> forensics@forensics-XPS-13-9365:~/mvt$ mvt-ios check-backup --output ~/Documents/iphone/output ~/Documents/iphone/00008020-001D54200101002E/
> 15:41:59 INFO     [mvt.ios.cli] Checking iTunes backup located at:             
>                   /home/forensics/Documents/iphone/00008020-001D54200101002E/  
>          INFO     [mvt.ios.modules.fs.safari_browserstate] Running module      
>                   SafariBrowserState...                                        
>          ERROR    [mvt.ios.modules.fs.safari_browserstate] There might be no   
>                   data to extract by module SafariBrowserState: Unable to find 
>                   the module's database file                                   
>          INFO     [mvt.ios.modules.fs.safari_history] Running module           
>                   SafariHistory...                                             
>          ERROR    [mvt.ios.modules.fs.safari_history] There might be no data to
>                   extract by module SafariHistory: Unable to find the module's 
>                   database file                                                
>          INFO     [mvt.ios.modules.fs.net_datausage] Running module            
>                   Datausage...                                                 
>          INFO     [mvt.ios.modules.fs.net_datausage] Found DataUsage database  
>                   at path: /home/forensics/Documents/iphone/00008020-001D542001
>                   01002E/0d/0d609c54856a9bb2d56729df1d68f2958a88426b           
>          INFO     [mvt.ios.modules.fs.net_datausage] Extracted information on  
>                   7133 processes                                               
> 15:42:00 INFO     [mvt.ios.modules.fs.sms] Running module SMS...               
>          INFO     [mvt.ios.modules.fs.sms] Found SMS database at path: /home/fo
>                   rensics/Documents/iphone/00008020-001D54200101002E/3d/3d0d7e5
>                   fb2ce288813306e4d4636395e047a3d28                            
> 15:42:01 INFO     [mvt.ios.modules.fs.sms] Extracted a total of 745 SMS        
>                   messages containing links                                    
>          INFO     [mvt.ios.modules.fs.sms_attachments] Running module          
>                   SMSAttachments...                                            
>          INFO     [mvt.ios.modules.fs.sms_attachments] Found SMS database at   
>                   path: /home/forensics/Documents/iphone/00008020-001D542001010
>                   02E/3d/3d0d7e5fb2ce288813306e4d4636395e047a3d28              
>          INFO     [mvt.ios.modules.fs.sms_attachments] Extracted a total of    
>                   3483 SMS attachments                                         
>          INFO     [mvt.ios.modules.fs.chrome_history] Running module           
>                   ChromeHistory...                                             
>          INFO     [mvt.ios.modules.fs.chrome_history] Found Chrome history     
>                   database at path: /home/forensics/Documents/iphone/00008020-0
>                   01D54200101002E/fa/faf971ce92c3ac508c018dce1bef2a8b8e9838f1  
>          INFO     [mvt.ios.modules.fs.chrome_history] Extracted a total of 60  
>                   history items                                                
>          INFO     [mvt.ios.modules.fs.chrome_favicon] Running module           
>                   ChromeFavicon...                                             
>          INFO     [mvt.ios.modules.fs.chrome_favicon] Found Chrome favicon     
>                   cache database at path: /home/forensics/Documents/iphone/0000
>                   8020-001D54200101002E/55/55680ab883d0fdcffd94f959b1632e5fbbb1
>                   8c5b                                                         
>          INFO     [mvt.ios.modules.fs.chrome_favicon] Extracted a total of 42  
>                   favicon records                                              
>          INFO     [mvt.ios.modules.fs.webkit_session_resource_log] Running     
>                   module WebkitSessionResourceLog...                           
> Traceback (most recent call last):
>   File "/home/forensics/.local/bin/mvt-ios", line 8, in <module>
>     sys.exit(cli())
>   File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/home/forensics/.local/lib/python3.8/site-packages/mvt/ios/cli.py", line 102, in check_backup
>     run_module(m)
>   File "/home/forensics/.local/lib/python3.8/site-packages/mvt/common/module.py", line 146, in run_module
>     module.check_indicators()
>   File "/home/forensics/.local/lib/python3.8/site-packages/mvt/ios/modules/fs/webkit_session_resource_log.py", line 84, in check_indicators
>     if self.indicators.check_domains(all_origins):
> AttributeError: 'NoneType' object has no attribute 'check_domains'
> ```
