### ISSUE TITLE
How to install MVT without pip or PyPi

### ISSUE THREAD

**Issue by bkgrrl00** [mvt-project/mvt#357]
Is it possible to install MVT without pip or PyPi, perhaps using a Python virtual environment?

I was able to install MVT via pip, but this caused my VPN (ProtonVPN) to stop working. [This article](https://protonvpn.com/support/pip-pypi/) in the Proton knowledge base warns users that pip and PyPi can cause the ProtonVPN to stop working. Not having a VPN can increase the risk of spyware. It would be ironic if, as a result of installing a spyware detection tool, my computer became infected with spyware.

**Comment by kpcyrd** [comment]
There's a [list of Linux distributions that ship MVT in their repositories](https://repology.org/project/mvt/versions).

Python programs are notoriously difficult to distribute, the official instructions already work with virtual environments but you need to know how to use them:

```
python3 -m venv virtual-env
source virtual-env/bin/activate
pip install mvt

mvt-android --help
```

**Comment by Te-k** [comment]
@kpcyrd is right, using [virtualenv](https://virtualenv.pypa.io/en/latest/) should solve your problem.

**Comment by bkgrrl00** [comment]
Thanks [kpcyrd](https://github.com/kpcyrd) and [Te-k](https://github.com/Te-k). I'll check out virtualenv and I may also check out of the Linux distros that come with MVT
