### ISSUE TITLE
Cannot run it (Ubuntu 22.04)

### ISSUE THREAD

**Issue by programmin1** [mvt-project/mvt#375]
I installed with

pip3 install mvt

Now I don't have "mvt-android" command available, nor

python3 -m mvt-python

**Comment by Forchapeatl** [comment]
Hi , these steps did the trick for me.

> `sudo apt install python3 python3-pip libusb-1.0-0 sqlite3`
>`export PATH=$PATH:~/.local/bin`
>`pip3 install mvt`

refernce  [MVT installation](https://docs.mvt.re/en/latest/install/) guide

**Comment by programmin1** [comment]
I did install it - that gives a bunch of "Requirement already satisfied:" lines.

now how do you run it?

**Comment by Forchapeatl** [comment]
`mvt-android`  command should be available now.  Dose the command work now ?

**Comment by Te-k** [comment]
Hi, this is described in the [MVT documentation](https://docs.mvt.re/en/latest/install/), as @Forchapeatl said, you need to add the binaries in your path.
