### ISSUE TITLE
Check for Lockdown Mode when running mvt-ios

### ISSUE THREAD

**Issue by runasand** [mvt-project/mvt#384]
Would be great for mvt-ios to check if Lockdown Mode is enabled on the device and print a warning, similar to the one for an out of date operating system, if the feature is not enabled.

**Comment by DonnchaC** [comment]
The most recent version of MVT adds support to determine if a phone has Lockdown mode enable. Currently the Lockdown Mode status is logged as an info message but we could consider updating that to a warning in future. As it's an optional feature in iOS at the moment we don't make the logs to noise if Lockdown mode is not enabled.

https://github.com/mvt-project/mvt/blob/c719c4da1ecb06f807c41ceb740deedbd0dbad82/mvt/ios/modules/mixed/global_preferences.py#L41-L45

**Comment by runasand** [comment]
I like the idea of upgrading the status from info to warning. The people who tend to use MVT to check for sophisticated spyware are the same people who would benefit from using Lockdown Mode to defend against it.

**Comment by Te-k** [comment]
I think it is a good idea to highlight it a bit more, it's done in 04b44826b4eb76238862c465240aa99b7944febd

**Comment by DonnchaC** [comment]
@runasand Does this cover the use case you had in mind? Feel free to reopen if you have other ideas
