### ISSUE TITLE
Issue with Doc SSL Certificate

### ISSUE THREAD

**Issue by RSickenberg** [mvt-project/mvt#39]
Hi, I think you are aware of this but I cannot go to the documentation due to a cert error.

Thanks for what you did!

![image](https://user-images.githubusercontent.com/16922548/126466772-dc13544b-7c97-4112-b67f-4ded585d1b96.png)

**Comment by botherder** [comment]
You might want to report issues with readthedocs here (it's a third-party service we do not maintain):
https://github.com/readthedocs
