### ISSUE TITLE
Path Error

### ISSUE THREAD

**Issue by G8YTZ** [mvt-project/mvt#40]
I'm really struggling with this error, I cannot see anything wrong with the path I'm using (Mac Catalina, iPhone 8) I've substituted and underscore for the space in the Application Support directory as it does not like the space. Backup was made non-encrypted.
```
 mvt-ios check-backup --output /Users/myusername/Downloads/ /Users/myusername/Library/Application_Support/MobileSync/Backup/9991553689f396bfc931039407d593096102ff4b/

Error: Invalid value for 'BACKUP_PATH': Path '/Users/myusername/Library/Application_Support/MobileSync/Backup/9991553689f396bfc931039407d593096102ff4b/' does not exist.
```

**Comment by botherder** [comment]
Are you sure your user has permission to access that folder from the terminal app you are using? You might need to enable filesystem access from your Mac settings to your terminal app.

**Comment by G8YTZ** [comment]
Yes, that's ok. I can navigate to the directory ok via terminal

**Comment by blooodorange** [comment]
same here:
"Error: Missing argument 'BACKUP_PATH'"

Running macOS 11.3

**Comment by botherder** [comment]
If you move the backup folder to another path, does that work?

**Comment by blooodorange** [comment]
> If you move the backup folder to another parent (e.g. home or desktop), does that work?

moved the backup folder to Downloads - same issues...

**Comment by Te-k** [comment]
Could you show is what ` mvt-ios check-backup --help` gives you? I really don't understand where this issue could come from

**Comment by botherder** [comment]
> > If you move the backup folder to another parent (e.g. home or desktop), does that work?
> 
> moved the backup folder to Downloads - same issues...

You are getting a different error though... Missing argument isn't the same as Invalid value. Please make sure you are launching the command correctly, and let's try to remain on topic.

Closing this for now as we've not heard from @G8YTZ in a while.
