### ISSUE TITLE
Missing file configuration_profiles.json

### ISSUE THREAD

**Issue by digits16** [mvt-project/mvt#401]
Hi, 

I see no configuration_profiles.json in the output. As I got from the description [here](https://docs.mvt.re/en/latest/ios/records/#configuration_profilesjson) it should be produced with info of default iOS profile at least. 

In my command.log I see only this 

`2023-09-26 20:22:13,284 - mvt.ios.modules.backup.configuration_profiles - INFO - Running module ConfigurationProfiles...
2023-09-26 20:22:13,287 - mvt.ios.modules.backup.configuration_profiles - INFO - Extracted details about 0 configuration profiles`

Could you please clarify? 

Thank you!

**Comment by Te-k** [comment]
Hi,

This file is only created if configuration profiles are found. In your case, it looks like there was no configuration profile so the file wasn't created.
