### ISSUE TITLE
Grabing dumps

### ISSUE THREAD

**Issue by thejoker3000** [mvt-project/mvt#42]
This might be a dumb thing but I don't know how to do it.
How do I grab the dump from my iphone to be able to run mvt-ios properly?

**Comment by pkirkovsky** [comment]
[Backup with iTunes app](https://mvt-docs.readthedocs.io/en/latest/ios/backup/itunes.html) or [Backup with libimobiledevice](https://mvt-docs.readthedocs.io/en/latest/ios/backup/libimobiledevice.html)

**Comment by thejoker3000** [comment]
Thanks. Didn't think of that. I'm a n00b with these things and just learning.
