### ISSUE TITLE
2 Filesystem tests fail on macOS only

### ISSUE THREAD

**Issue by roaree** [mvt-project/mvt#429]
Only impacts development AFAICT. Would be good to track down a root cause.

```
FAILED tests/ios_fs/test_filesystem.py::TestFilesystem::test_filesystem - AssertionError: assert 17 == 15
FAILED tests/ios_fs/test_filesystem.py::TestFilesystem::test_detection - AssertionError: assert 17 == 15
```

When the tests fail it leaves behind two artifacts on disk:

```
	tests/artifacts/ios_backup/64/64d0019cb3d46bfc8cce545a8ba54b93e7ea9347-shm
	tests/artifacts/ios_backup/64/64d0019cb3d46bfc8cce545a8ba54b93e7ea9347-wal
```

**Comment by roaree** [comment]
Running only `pytest tests/ios_fs/test_filesystem.py` works fine - I think one of the other test modules must be leaving behind these artifacts, interfering with this module's tests.

**Comment by DonnchaC** [comment]
I think there is an issue with the SQLite driver on OS X. It loads the SQLite databases. created the temporary write-ahead-log and keeps does around until the process finished IIRC.

https://github.com/groue/GRDB.swift/issues/739#issuecomment-624483632
