### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by dnalexen** [mvt-project/mvt#43]
Hello, when I executed this command 'mvt-android download-apks --output apks', I got this error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/.android/adbkey'

Do you know how to solve that bug?

**Comment by goshawk22** [comment]
Have to installed adb?

**Comment by dnalexen** [comment]
I have adb-shell version 0.4.0 install by the command 'pip install .'

**Comment by goshawk22** [comment]
What happends when you run the command `adb devices`?

**Comment by dnalexen** [comment]
I have that:
List of devices attached
* daemon not running; starting now at tcp:zzzz
* daemon started successfully
XXXXXXXXXXXXXX	unauthorized

**Comment by dnalexen** [comment]
It's ok now. I gave my pc the authorization to access my phone.
