### ISSUE TITLE
MVT on openSUSE Linux?

### ISSUE THREAD

**Issue by Citizen839X** [mvt-project/mvt#453]
Is there a way to install Mobile Verification Toolkit on openSUSE Linux correctly? 

Did anyone test on it?

**Comment by Lordakius** [comment]
I don't use openSUSE at all, but there is [python3](https://software.opensuse.org/package/python3) available. 

So you could go ahead and try the recommended way:
```
pip3 install mvt
```

although eventually you would want to use venv

**Comment by Te-k** [comment]
Thanks @Lordakius for the help, indeed, it should work on OpenSuse through pip without issue. Please let us know if you encounter any problem
