### ISSUE TITLE
mvt-ios fehlermeldung

### ISSUE THREAD

**Issue by FranzWaismayer** [mvt-project/mvt#457]
an alle

ich habe folgendes problem,
nachdem ich das tool installiert habe und nach den vorgaben das tool gestartet und die befehle eingegeben habe, erscheint nachfolgende fehlermeldung.

weiß wer einen rat, was ich falsch gemacht habe?

![mvt-ios_fehlermeldung](https://github.com/mvt-project/mvt/assets/79380033/f00cff64-5aab-4f62-b442-daea6776e7aa)

bei verschiedenen videos startete das program vor der letzten fehlermeldung selbstständig.

**Comment by JustBadCoder** [comment]
Hi
When you take a backup of iOS to your computer, make sure that the backup is encrypted. Mark in iTunes / macOS Finder, to encrypt the backup and give it an easy password.

**Comment by FranzWaismayer** [comment]
> Hallo,
> wenn Sie ein iOS-Backup auf Ihrem Computer erstellen, stellen Sie sicher, dass das Backup verschlüsselt ist. Markieren Sie im iTunes / macOS Finder, um das Backup zu verschlüsseln und ihm ein einfaches Passwort zu geben.

Meines Wissens habe ich ein Passwort vergeben. Falls kein Passwort vergeben sein sollte, wie sollte der Code in der Befehlszeile lauten?

**Comment by JustBadCoder** [comment]
I am not sure what command to be used, when there is no password. I was under the impression that you MUST use a password, ie the backup is encrypted.
