### ISSUE TITLE
mvt-ios error in iOSbackup

### ISSUE THREAD

**Issue by reivaj78** [mvt-project/mvt#46]
When using  mvt-ios decrypt-backup, an exception error arise stopping the process

Exception ignored in: <function iOSbackup.__del__ at 0x110652820>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/iOSbackup/__init__.py", line 132, in __del__
    self.close()
  File "/usr/local/lib/python3.9/site-packages/iOSbackup/__init__.py", line 138, in close
    os.remove(self.manifestDB)
TypeError: remove: path should be string, bytes or os.PathLike, not NoneType

**Comment by dbl001** [comment]
I got the same error on Catalina as well as with Big Sur with python 3.6.

**Comment by reivaj78** [comment]
> When using mvt-ios decrypt-backup, an exception error arise stopping the process
> 
> Exception ignored in: <function iOSbackup.**del** at 0x110652820>
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/iOSbackup/**init**.py", line 132, in **del**
> self.close()
> File "/usr/local/lib/python3.9/site-packages/iOSbackup/**init**.py", line 138, in close
> os.remove(self.manifestDB)
> TypeError: remove: path should be string, bytes or os.PathLike, not NoneType

I found the issue, the backup password has a redirecting character '>' that needed to be escaped. 
Once escaped, the issue is resolved
