### ISSUE TITLE
Getting a "No device found" error message

### ISSUE THREAD

**Issue by Theeverydayman** [mvt-project/mvt#471]
Hey, I keep getting a "Device not found" error for some reason:

> INFO     [mvt.android.cmd_check_adb] Loaded a total of 9670 unique indicators
> INFO     [mvt] Checking Android device over debug bridge
> INFO     [mvt.android.modules.adb.chrome_history] Running module ChromeHistory...
> CRITICAL [mvt.android.modules.adb.chrome_history] No device found. Make sure it is connected and unlocked.

Phone connected via USB to a Windows 11 laptop, running Linux Subsystem on it. Debugging is enabled on the phone, and the device is authorized for it. ADB devices command shows that the phone is in fact connected: 

> └─$ adb devices
> List of devices attached
> xx.xxx.xxx.xx:5555      device

[5555 because I had to start adb tcpip on windows to make it visible in WSL]

Basically, my phone is connected, authorized and visible in ADB, yet MVT shows a no device error. Tried restarting the whole machine too.

Any ideas?

# UPDATE:
Made it work. For future reference:
`mvt-android check-adb` command alone shows no device [no clue if it should work, info on google suggests it should, if not then a "you need to specify target" message is recommended to avoid confusion]

`mvt-android check-adb -s DEVICEIP:PORT` has worked.

**Comment by roaree** [comment]
Glad you got sorted. For reference, there are some docs on using `adb tcpip` and the `check-adb --serial` option here: https://docs.mvt.re/en/latest/android/adb/
