### ISSUE TITLE
Possible wrong suspicious app

### ISSUE THREAD

**Issue by fmanci** [mvt-project/mvt#487]
Hello,
as part of an MVT check, I got this result: Suspicious app not installed from the App Store or MDM: nz.co.daru.morpion

Does someone know what is this app? I have the approved EU AltStore on iOS and it detected it and Delta, which I downloaded from there.
May it be another "ghost" app from AltStore?

Thanks

**Comment by Te-k** [comment]
Hi!
This alert is flagging any app not installed from apple store or by MDM, so it totally make sense that it is being flagged by MVT. 
For documentation purpose, could you share the content of the file `applications_detected.json`? (feel free to remove any private information in it)

**Comment by fmanci** [comment]
Hello, I haven't installed anything else except AltStore and Delta, I don't know what that Morpion is but I will share the file. If you tell me it's possible that a ghost app has been created, is fine.
I am attaching the file where it says it's "Tic Tac Toe game for iMessage!". Again, I don't know what it is.
[applications_detected.json](https://github.com/mvt-project/mvt/files/15029440/applications_detected.json)

**Comment by DrWhax** [comment]
I think it's this: https://apps.apple.com/cm/app/morpion-jeu-pour-imessage/id1153229042

**Comment by Te-k** [comment]
Thanks for sharing! I have deleted the file you shared from the issue as it contained your icloud account address.
Yes; that's the app @DrWhax mentioned ["Tic Tac Toe game for iMessage!"](https://apps.apple.com/us/app/tic-tac-toe-game-for-imessage/id1153229042) in english. It looks like you installed it on 2022-03-06 and it is from the appstore indeed, but somehow the source app mentioned is `com.apple.MobileSMS`. Do you remember how you installed that app by any chance? It may be a change in the application format

**Comment by fmanci** [comment]
If I look on iMessage I can find the Tic Tac Toe. I don't remember installing it but it's more than plausible I did it myself.
In any case I highly doubt I installed it outside the App Store, also because I don't have any profile installed relating to it, so I don't really know what's the reason for the flag.
Thanks again for the help
