### ISSUE TITLE
Tools for Analysis of APKs after download

### ISSUE THREAD

**Issue by ShechemKS** [mvt-project/mvt#50]
Using `mvt-android download-apks`, a user is able to download the APKs on an android phone. However, the documentation does not point users to any useful tools to subsequently analyze the APKs once they have been downloaded. 
- Are there such tools available? 
- Are they integrated into MVT? 
- Are there any useful verified 3rd party tools? 

Any information would be helpful.
The given instructions only indicate how to use VirusTotal, Koodous or "All Checks" while downloading, without specifying how to run those after downloading, or what All Checks include.

**Comment by SnaSana111** [comment]
I think you can upload them to Virustotal or Koodous for analysis as it says here on this page:

https://mvt.readthedocs.io/en/latest/android/download_apks.html

**Comment by Te-k** [comment]
[sdanalyzer](https://github.com/Te-k/sdanalyzer) can also help.
