### ISSUE TITLE
adb device not found

### ISSUE THREAD

**Issue by Nader-B10** [mvt-project/mvt#520]
![Screenshot 2024-08-17 173912](https://github.com/user-attachments/assets/b100dec2-860b-4fd4-9a3a-b6f827b1c947)

**Comment by kpcyrd** [comment]
I'm guessing here but I suspect this is because of mvt being inside of WSL and adb being outside of WSL. There's a [stackoverflow answer](https://stackoverflow.com/a/65242444) that might be relevant:



> On Windows:
>
> ```
> adb tcpip 5555
> ```
>
> Then on WSL 2:
>
> ```
> adb connect [ip device]:5555
> ```
>
> If it's the first time, it's going to ask you for permission in your phone, make sure to check the box to always grant permission. Then restart adb and connect again:
>
> ```
> adb kill-server
> adb connect [ip device]:5555
> ```
>
> You can get your [ip device] from: Settings > About device > Status. It has a form like: 170.100.100.100

**Comment by Nader-B10** [comment]
What should I do? Isn't there a video or blog that explains how to do this? I'm not an expert in these matters. I'm trying to understand the main things that were written, then copy and paste the codes. I don't understand anything. I just follow the instructions.

**Comment by Nader-B10** [comment]
I received this email yesterday, which was blackmail, ransom demand, and a claim to use Pegasus software. I don’t know if this is true or if it is a scam email that just wants me to transfer money. I don’t have the money he is asking for, so since yesterday I have been searching for a tool to scan my device to check for any virus and whether what he is saying is true or not. Unfortunately, until now, I have a problem similar to the one in the picture, and I don’t know how to solve it. There are still hours left until the deadline he mentioned to me. I searched for the virus that he claims to have installed on my device, and it is said that it is from an Israeli company and is provided to government agencies, not to the public, and costs thousands of dollars to hack a device and targets leaders of countries and celebrities. I am just an ordinary person, so I did not see it logical that his words are true. I am not an important person, and I do not think he will ask for only $851, and using the virus costs thousands of dollars.
![Screenshot 2024-08-17 182233](https://github.com/user-attachments/assets/8010ec39-7149-4269-9fdf-c92cae9a0a76)

**Comment by kpcyrd** [comment]
This is a common spam email that is automatically being sent to a large amount of email addresses, they are trying to scare you but you can safely ignore this email, they have nothing and your phone is fine.

> Isn't there a video or blog that explains how to do this? I'm not an expert in these matters. I'm trying to understand the main things that were written, then copy and paste the codes. I don't understand anything. I just follow the instructions.

I think most people use this tool on Linux or MacOS, getting it to work on Windows is more complicated but the reasons for this are very technical and boring.

**Comment by Te-k** [comment]
Indeed, MVT doesn't support Windows so far, see the documentation [here](https://docs.mvt.re/en/latest/install/). I totally agree wiht @kpcyrd answer and assessment here (and thanks @kpcyrd !)

I am closing this issue, feel free to reopen it if you encounter issues in MVT on Linux or MacOS

**Comment by Clayblockunova** [comment]
> This is a common spam email that is automatically being sent to a large amount of email addresses, they are trying to scare you but you can safely ignore this email, they have nothing and your phone is fine. :)
> 
> > Isn't there a video or blog that explains how to do this? I'm not an expert in these matters. I'm trying to understand the main things that were written, then copy and paste the codes. I don't understand anything. I just follow the instructions.
> 
> I think most people use this tool on Linux or MacOS, getting it to work on Windows is more complicated but the reasons for this are very technical and boring.

sorry for ask you at now. how complicated it is? why Zadig can't fix that?
