### ISSUE TITLE
Hardcoded API Key for VirusTotal

### ISSUE THREAD

**Issue by NicolasCARPi** [mvt-project/mvt#54]
Hello,

I believe it is an error to hardcode the apikey for virustotal api requests (see https://github.com/mvt-project/mvt/blob/main/mvt/android/lookups/virustotal.py#L16).

You might want to let the end user provide one through a config option instead.

**Comment by Te-k** [comment]
It is a key that has been used for a while by many tools, not a personal key of anyone

**Comment by NicolasCARPi** [comment]
Ok, all good then :)
