### ISSUE TITLE
Check if Pegasus virus infected a device

### ISSUE THREAD

**Issue by Vins-222** [mvt-project/mvt#58]

**Comment by pkirkovsky** [comment]
Grab the Pegasus IOCs from [here](https://github.com/AmnestyTech/investigations/tree/master/2021-07-18_nso). The important file is `pegasus.stix2`. Then, point the tool to it using the `-i, --iocs` option with `check-backup`

**Comment by wtroisey** [comment]
Thanks for updating doc. Is iTunes backup sufficient to determine if a device has been infected? Or will I need a complete filesystem dump?
