### ISSUE TITLE
Error: Missing argument 'BACKUP_PATH'.

### ISSUE THREAD

**Issue by ziaalian** [mvt-project/mvt#59]
I have copied my encrypted backup file from ~/library/Applicationsupport/mobilesync/Backup
to desktop.
then i'm typing this command to decrypt the file `mvt-ios decrypt-backup -p PASSWORD -d ~/Desktop/Backup`

and i'm getting this error:
 
`Usage: mvt-ios decrypt-backup [OPTIONS] BACKUP_PATH
Try 'mvt-ios decrypt-backup --help' for help.

Error: Missing argument 'BACKUP_PATH'.

**Comment by Te-k** [comment]
Yes, `-d` is for the output folder not for the backup path, you also need to provide the backup folder (which is explained if you look at the help).

**Comment by ziaalian** [comment]
thanks Te for your reply, 
Can you explain what is the output folder. and what the exact command should be like to decrypt the files after backing it up from iTunes and copy the folder to the desktop?
