### ISSUE TITLE
Android check-backup 

### ISSUE THREAD

**Issue by mfrederick98** [mvt-project/mvt#60]
my decrypted sms are in this path after abe.jar process from backup.ab to backup.tar, then extracted files get dumped to the below path.

C:\adb\backup\apps\com.android.providers.telephony\d_f

My error, check-backup is not seeing them.  I did not use a password to backup, since it was not required.

![Screenshot 2021-07-22 035843-check-backup](https://user-images.githubusercontent.com/8031924/126606838-887d5535-fc99-4aae-8ae7-e089fe665dd8.jpg)

**Comment by Te-k** [comment]
As described [here](https://mvt.readthedocs.io/en/latest/android/backup.html), you need to provide the folder of extraction (here `C:\adb\backup`) and not the folder with the json file in parameters.
