### ISSUE TITLE
mvt-ios decrypt backup issue with certain password.

### ISSUE THREAD

**Issue by samsonho** [mvt-project/mvt#62]
Running on BigSur, when executing mvt-ios decrypt-backup, python errors are generated when specifying passwords trailing with the 'bang' aka '!' character. Let me know if you want an screen shots etc. Thanks!

**Comment by Te-k** [comment]
have you tried to put it into quotes?

**Comment by tritium01** [comment]
> have you tried to put it into quotes?

Getting the same error, tried single and double quotes but no positive result

**Comment by pkirkovsky** [comment]
Try running it with a trailing (and empty) `-p` flag. That should prompt for a password.

**Comment by tritium01** [comment]
> Try running it with a trailing (and empty) `-p` flag. That should prompt for a password.

Modified to print the password entered, it seems to be displaying it correctly, but still saying wrong password. Tried with two different files and Iphones, resetting settings and setting a new encryption password still no luck.

Can the extract-key PR help out with this issue?
Attached is the Typerror shown in console.
Thanks for the help great proyect!

`
❯ mvt-ios decrypt-backup2 --password "123456" -d ../../backups/rmg ../../backups/00008101-000C08303498001E
12:52:40 INFO     [mvt.ios.decrypt] Decrypting iOS backup at path ../../backups/00008101-000C08303498001E with password                                                                                                      
12:52:45 ERROR    [mvt.ios.decrypt] b'KEY'                                                                                                                                                                                   
                  Traceback (most recent call last):                                                                                                                                                                         
                    File "/Users/rmg/.local/share/virtualenvs/mvt-4CIRQtEM/lib/python3.9/site-packages/mvt/ios/decrypt.py", line 75, in decrypt_with_password                                                                
                      self._backup = iOSbackup(udid=os.path.basename(self.backup_path),                                                                                                                                      
                    File "/Users/rmg/.local/share/virtualenvs/mvt-4CIRQtEM/lib/python3.9/site-packages/iOSbackup/__init__.py", line 190, in __init__                                                                         
                      self.getManifestDB()                                                                                                                                                                                   
                    File "/Users/rmg/.local/share/virtualenvs/mvt-4CIRQtEM/lib/python3.9/site-packages/iOSbackup/__init__.py", line 1037, in getManifestDB                                                                   
                      key = self.unwrapKeyForClass(manifest_class, manifest_key)                                                                                                                                             
                    File "/Users/rmg/.local/share/virtualenvs/mvt-4CIRQtEM/lib/python3.9/site-packages/iOSbackup/__init__.py", line 1150, in unwrapKeyForClass                                                               
                      ck = self.classKeys[protection_class][b"KEY"]                                                                                                                                                          
                  KeyError: b'KEY'                                                                                                                                                                                           
         CRITICAL [mvt.ios.decrypt] Failed to decrypt backup. Did you provide the correct passwords? 123456                                                                                                                
Exception ignored in: <function iOSbackup.__del__ at 0x1091951f0>
Traceback (most recent call last):
  File "/Users/rmg/.local/share/virtualenvs/mvt-4CIRQtEM/lib/python3.9/site-packages/iOSbackup/__init__.py", line 132, in __del__
    self.close()
  File "/Users/rmg/.local/share/virtualenvs/mvt-4CIRQtEM/lib/python3.9/site-packages/iOSbackup/__init__.py", line 138, in close
    os.remove(self.manifestDB)
TypeError: remove: path should be string, bytes or os.PathLike, not NoneType`

**Comment by pkirkovsky** [comment]
>Can the extract-key PR help out with this issue?

Possibly. Give it a try!

>Attached is the Typerror shown in console.

Yeah, the underlying library is not very graceful about handling errors. I will investigate this further.
Also, I'll double check how MVT processes special characters, as I've seen some issues when attempting to quote parameter values.

**Comment by botherder** [comment]
Can you check you do have a `Manifest.db` file inside the backup folder and that it is not empty?

**Comment by merganon** [comment]
> > Try running it with a trailing (and empty) `-p` flag. That should prompt for a password.
> 
> Modified to print the password entered, it seems to be displaying it correctly, but still saying wrong password. Tried with two different files and Iphones, resetting settings and setting a new encryption password still no luck.
> 
> Can the extract-key PR help out with this issue?
> Attached is the Typerror shown in console.
> Thanks for the help great proyect!
> 
> ```
> ❯ mvt-ios decrypt-backup2 --password "123456" -d ../../backups/rmg ../../backups/00008101-000C08303498001E
> 12:52:40 INFO     [mvt.ios.decrypt] Decrypting iOS backup at path ../../backups/00008101-000C08303498001E with password                                                                                                      
> 12:52:45 ERROR    [mvt.ios.decrypt] b'KEY'                                                                                                                                                                                   
>                   Traceback (most recent call last):                                                                                                                                                                         
>                     File "/Users/rmg/.local/share/virtualenvs/mvt-4CIRQtEM/lib/python3.9/site-packages/mvt/ios/decrypt.py", line 75, in decrypt_with_password                                                                
>                       self._backup = iOSbackup(udid=os.path.basename(self.backup_path),                                                                                                                                      
>                     File "/Users/rmg/.local/share/virtualenvs/mvt-4CIRQtEM/lib/python3.9/site-packages/iOSbackup/__init__.py", line 190, in __init__                                                                         
>                       self.getManifestDB()                                                                                                                                                                                   
>                     File "/Users/rmg/.local/share/virtualenvs/mvt-4CIRQtEM/lib/python3.9/site-packages/iOSbackup/__init__.py", line 1037, in getManifestDB                                                                   
>                       key = self.unwrapKeyForClass(manifest_class, manifest_key)                                                                                                                                             
>                     File "/Users/rmg/.local/share/virtualenvs/mvt-4CIRQtEM/lib/python3.9/site-packages/iOSbackup/__init__.py", line 1150, in unwrapKeyForClass                                                               
>                       ck = self.classKeys[protection_class][b"KEY"]                                                                                                                                                          
>                   KeyError: b'KEY'                                                                                                                                                                                           
>          CRITICAL [mvt.ios.decrypt] Failed to decrypt backup. Did you provide the correct passwords? 123456                                                                                                                
> Exception ignored in: <function iOSbackup.__del__ at 0x1091951f0>
> Traceback (most recent call last):
>   File "/Users/rmg/.local/share/virtualenvs/mvt-4CIRQtEM/lib/python3.9/site-packages/iOSbackup/__init__.py", line 132, in __del__
>     self.close()
>   File "/Users/rmg/.local/share/virtualenvs/mvt-4CIRQtEM/lib/python3.9/site-packages/iOSbackup/__init__.py", line 138, in close
>     os.remove(self.manifestDB)
> TypeError: remove: path should be string, bytes or os.PathLike, not NoneType
> ```

A quick fix is to use a password without special characters

**Comment by samsonho** [comment]
> have you tried to put it into quotes?

Yes

**Comment by samsonho** [comment]
> Can you check you do have a `Manifest.db` file inside the backup folder and that it is not empty?

It is present and it is not empty.

**Comment by samsonho** [comment]
> A quick fix is to use a password without special characters

Unfortunately this was my temporary solution. 😵‍💫👍🏻

**Comment by botherder** [comment]
As of the latest version you can now pass a password by command line, by environment var or by prompt. Surely one option would work for you.

I'm closing this ticket as resolved.
