### ISSUE TITLE
mvt-android command not recognized after instllation

### ISSUE THREAD

**Issue by MasterJedi1** [mvt-project/mvt#64]
I was just curious to check this out since I was reading about the Pegasus story just yesterday.

I did enable developper mode and went through the different steps, though it seems that even after installing mvt with python doesn't git access to mvt-android nor mvt-ios.
It doesn't seem to detect it or to recognize the commands (I have a backup of android to anaylyze).
"'mvt' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes."

I may have forgotten something but I don't see what...
Feel free to answer.

**Comment by goshawk22** [comment]
`export PATH=$PATH:~/.local/bin`

See https://mvt.readthedocs.io/en/latest/install.html#installing-mvt

**Comment by MasterJedi1** [comment]
thanks @goshawk22 but it seems that "export" is not recognized either.
I forgot to mention that i'm on Windows (not mac).

Should I add the location of the mvt bin manually to the environment variables ?
> `export PATH=$PATH:~/.local/bin`
> 
> See https://mvt.readthedocs.io/en/latest/install.html#installing-mvt

**Comment by goshawk22** [comment]
> Should I add the location of the mvt bin manually to the environment variables ?

Yes try this

**Comment by MasterJedi1** [comment]
it doesn't seem that adding "~\.local\bin" solves the problem unfortunatelly.....
I'm probably missing something

**Comment by Te-k** [comment]
It is a pypi issue not a mvt issue, you have to add the path of pypi binaries to your path
