### ISSUE TITLE
List of malicious indicators

### ISSUE THREAD

**Issue by wesgladwell** [mvt-project/mvt#65]
Hi, So I need a list of malicious indicators to make use of this app? If so, where can I find one.

**Comment by RoneoOrg** [comment]
Not sure, but maybe there: https://github.com/AmnestyTech/investigations

**Comment by wesgladwell** [comment]
> Not sure, but maybe there: https://github.com/AmnestyTech/investigations

Legendary.

**Comment by pkirkovsky** [comment]
See #58

**Comment by U039b** [comment]
You have to use the STIX file available at https://github.com/AmnestyTech/investigations/blob/master/2021-07-18_nso/pegasus.stix2 - it contains the IOCs.
