### ISSUE TITLE
   No superuser binary detected. Are you rooted?

### ISSUE THREAD

**Issue by madabit** [mvt-project/mvt#66]
When I write:
"$ sudo apt install python3"
The Termux says that:
              
"superuser binary detected.
Are you rooted?"
Is it mandatory to root to run this program??

**Comment by madabit** [comment]
![IMG_20210722_205553](https://user-images.githubusercontent.com/87820067/126660771-7ba29234-08ed-4418-a886-c2c73a895504.jpg)

Here is the ss

**Comment by U039b** [comment]
By invoking `sudo` you are asking for `root` privileges so yes, you have to be part of the `sudoer` group on your computer.

**Comment by hmidaouffai** [comment]
busybox
