### ISSUE TITLE
 ERROR: You must give at least one requirement to install (see "pip help install")

### ISSUE THREAD

**Issue by madabit** [mvt-project/mvt#67]
When I write:
$ pip3 install      
Termux shows me error  like this:                       
   "  ERROR: You must give at least one requirement to install (see "pip help install")
"
What to do now?
![IMG_20210722_210937](https://user-images.githubusercontent.com/87820067/126662893-91678913-314d-4347-8ee1-060d6e50ff11.jpg)

**Comment by SnaSana111** [comment]
I had this issue. I ran the Github code from the website and that worked for me.

**Comment by Te-k** [comment]
You forgot the `.`, it is `pip3 install .`
