### ISSUE TITLE
When I write " mvt-android" command I'm facing big garbage error

### ISSUE THREAD

**Issue by madabit** [mvt-project/mvt#68]
What can I do?

**Comment by madabit** [comment]
![IMG_20210722_215204](https://user-images.githubusercontent.com/87820067/126669579-dfd7bbe0-837b-420a-a526-2940443ac8b3.jpg)
![IMG_20210722_215218](https://user-images.githubusercontent.com/87820067/126669588-cb14ae22-282a-4c04-8fd6-85bd9d52a550.jpg)

**Comment by laundmo** [comment]
if you read through the installation docs you will find that it specifies you need to install libusb. the error says it couldn't find the libusb installation 

https://mvt.readthedocs.io/en/latest/install.html

**Comment by U039b** [comment]
AFAIK mvt is not designed to run on an Android device. You have to install it on your computer - not on the device you want to analyze.
