### ISSUE TITLE
mvt-android throws LIBUSB_ERROR_NOT_SUPPORTED [-12] on Windows 10

### ISSUE THREAD

**Issue by fnaat** [mvt-project/mvt#69]
I have just installed **mvt** via **pip** on a **Windows 10** machine and attached a Huawei P20 lite. The device is listed by adb, i.e. USB debugging works. However, when I try to issue `check-adb` or `download-apks`, `mvt-android` throws an error.

```
>adb devices -l
List of devices attached
9WV7N18303005029       device product:ANE-LX1 model:ANE_LX1 device:HWANE transport_id:2
```

```
>mvt-android check-adb
19:16:21 INFO     [mvt.android.cli] Checking Android through adb bridge
         INFO     [mvt.android.modules.adb.chrome_history] Running module ChromeHistory...
         CRITICAL [mvt.android.modules.adb.base] LIBUSB_ERROR_NOT_SUPPORTED [-12]
```

```
>mvt-android download-apks -o .
19:36:07 CRITICAL [mvt.android.modules.adb.base] LIBUSB_ERROR_NOT_SUPPORTED [-12]
```

Interestingly, `download-apks` was working somewhere before I hit the `check-adb` error. I only executed it again for the sake of this issue only to find out that it had stopped working. I have no idea why.

**Comment by botherder** [comment]
I have not tested it extensively on Windows, but the only time I got it to work I believe I had to recompile libusb under WSL.

**Comment by fnaat** [comment]
When searching for `LIBUSB_ERROR_NOT_SUPPORTED` and Windows 10, I came across [Zadig](https://zadig.akeo.ie/) (USB driver installation made easy). In theory it should support replacing USB drivers and thereby possibly solving this issue. For me it does not work though and I am not even too sure what this should exactly bring about then.

After enabling `Options -> List all devices` it shows me - amongst others - a device named **ADB Interface** with vendor ID Huawei Technologies. The current driver is WinUSB (v2.0.3.0) and replacing it with any other driver (e.g. libusb-win32 (v1.2.6.0)) or even updating to WinUSB (v6.1.7600.16385) does not work. `Driver installation: FAILED (Resource already exists).`

Maybe someone else can make sense of this or whether this is totally off-track.

**Comment by CodedK** [comment]
Same here on Windows. `List all devices` using `adb devices -l` shows my device.
But I get  `LIBUSB_ERROR_NOT_SUPPORTED` on all commands.

**Comment by geff10** [comment]
Same error here for Samsung Galaxy J5 (2016).

**Comment by pozso1234** [comment]
Same error here for Huawei P30 Lite MAR-LX1A
Build: 10.0.0.470 (C431E14R2P7)

**Comment by botherder** [comment]
I'm afraid this is not an issue with any mobile device. This is an issue with libusb and Windows. So far as Windows is not officially supported by mvt I don't think we'll be able to do much. The only advice I can give is to try to run MVT from WSL.

**Comment by geff10** [comment]
> Same error here for Samsung Galaxy J5 (2016).

Workaround what helped me: changing the driver using Zadig.

**Comment by fnaat** [comment]
> Workaround what helped me: changing the driver using Zadig.

Couple of questions:

1. For which device did you change the driver?
2. To which driver did you change it?
3. In which USB mode did you connect the smartphone (file transfer, photo transfer, just charging, ...)?

**Comment by botherder** [comment]
> > Same error here for Samsung Galaxy J5 (2016).
> 
> Workaround what helped me: changing the driver using Zadig.

This is also what is suggested on adb-shell repository:
https://github.com/JeffLIrion/adb_shell/issues/118

I would recommend following those instructions.

**Comment by botherder** [comment]
For the time being please check:
https://github.com/mvt-project/mvt/issues/125#issuecomment-900207043

We will add some notes on the documentation for Android users. Closing this for now.
