### ISSUE TITLE
Errors when downloading certain APKs

### ISSUE THREAD

**Issue by duyunov** [mvt-project/mvt#74]
You can close my previous tickets - I had issues with root rights on my Ubuntu for .android/adbkeys folder. It was successfully resolved. My current question is that there are certain APKs which still can't be downloaded. Most APKs are downloaded and checked as expected, but some cause following error:

0.00B [00:00, ?B/s]
         ERROR    [mvt.android.download_apks] Failed to pull package file from  
                  /vendor/overlay/FrameworkResOverlay/FrameworkResOverlay.apk:  
                  Unable to download file                                       
                  /vendor/overlay/FrameworkResOverlay/FrameworkResOverlay.apk:  
                  Command failed: open failed: Permission denied                
                  Traceback (most recent call last):                            
                    File "/home/eugene/.local/lib/python3.8/site-packages/mvt/an
                  droid/modules/adb/base.py", line 121, in _adb_download        
                      self.device.pull(remote_path, local_path,                 
                  progress_callback)                                            
                    File "/home/eugene/.local/lib/python3.8/site-packages/adb_sh
                  ell/adb_device.py", line 893, in pull                         
                      self._pull(device_path, stream, progress_callback,        
                  adb_info, filesync_info)                                      
                    File "/home/eugene/.local/lib/python3.8/site-packages/adb_sh
                  ell/adb_device.py", line 918, in _pull                        
                      for cmd_id, _, data in                                    
                  self._filesync_read_until([constants.DATA], [constants.DONE], 
                  adb_info, filesync_info):                                     
                    File "/home/eugene/.local/lib/python3.8/site-packages/adb_sh
                  ell/adb_device.py", line 1381, in _filesync_read_until        
                      cmd_id, header, data = self._filesync_read(expected_ids + 
                  finish_ids, adb_info, filesync_info)                          
                    File "/home/eugene/.local/lib/python3.8/site-packages/adb_sh
                  ell/adb_device.py", line 1320, in _filesync_read              
                      raise exceptions.AdbCommandFailureException('Command      
                  failed: {}'.format(reason))                                   
                  adb_shell.exceptions.AdbCommandFailureException: Command      
                  failed: open failed: Permission denied                        
                                                                                
                  During handling of the above exception, another exception     
                  occurred:                                                     
                                                                                
                  Traceback (most recent call last):                            
                    File "/home/eugene/.local/lib/python3.8/site-packages/mvt/an
                  droid/download_apks.py", line 138, in pull_package_file       
                      self._adb_download(remote_path, local_path,               
                    File "/home/eugene/.local/lib/python3.8/site-packages/mvt/an
                  droid/modules/adb/base.py", line 123, in _adb_download        
                      raise Exception(f"Unable to download file {remote_path}:  
                  {e}")                                                         
                  Exception: Unable to download file                            
                  /vendor/overlay/FrameworkResOverlay/FrameworkResOverlay.apk:  
                  Command failed: open failed: Permission denied

**Comment by U039b** [comment]
AFAIK, you need `root` privileges on your Android device to retrieve system apps - APK installed by the device manufacturer.

**Comment by Te-k** [comment]
Yep, exactly, so it is not a bug
