### ISSUE TITLE
Path to /python/ bash issue

### ISSUE THREAD

**Issue by BMWKingOC** [mvt-project/mvt#75]
I've spent over 9 hours in the last 2 days without any luck... How do I get MVT WORKING? I install it & just get errors
I don't understand the export path part?  I've tried over a dozen different path variations but not sure if correct?
 need to scan my backup.. 
Anyone willing to help me email me at bmwkingoc@gmail.com

I've reinstalled ubuntu over 10 times also to retry after errors by starting a fresh ubuntu install. Python is frustrating.
I've installed many things on Linux in the past following guides, but mvt documentation is not very clear to me.

`MVT installs.. 

user@DESKTOP-MK1RGJI:~$ python3 --version
Python 3.8.10
user@DESKTOP-MK1RGJI:~$ pip3 install mvt
Collecting mvt
  Downloading mvt-1.0.11-py3-none-any.whl (180 kB)
     |████████████████████████████████| 180 kB 3.5 MB/s
Collecting adb-shell`

`WARNING: The scripts pyrsa-decrypt, pyrsa-encrypt, pyrsa-keygen, pyrsa-priv2pub, pyrsa-sign and pyrsa-verify are installed in '/home/user/.local/bin' which is not on PATH.

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script cmark is installed in '/home/user/.local/bin' which is not on PATH.`

`user@DESKTOP-MK1RGJI:~/mvt$ mvt-ios
Traceback (most recent call last):
  File "/home/user/.local/bin/mvt-ios", line 5, in <module>
    from mvt.ios import cli
  File "/home/user/.local/lib/python3.8/site-packages/mvt/ios/__init__.py", line 6, in <module>
    from .cli import cli
  File "/home/user/.local/lib/python3.8/site-packages/mvt/ios/cli.py", line 53, in <module>
    def decrypt_backup(destination, password, key_file, backup_path):
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 173, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/home/user/.local/lib/python3.8/site-packages/mvt/common/options.py", line 23, in __init__
    super(MutuallyExclusiveOption, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1547, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'prompt_required'`

How do i make it on path? what do i type exactly, and where  ? bashc located where? I Just can't seem to figure it out

**Comment by BMWKingOC** [comment]
OK! I tried again.. still nothing works>>> OMG

29/fbf17084f81b849509e06a1bec40c04e3a9a15c14a0b202a78
Successfully built mvt biplist
Installing collected packages: pyasn1, rsa, adb-shell, biplist, pycryptodome, iOSbackup, libusb1, pygments, commonmark, rich, tld, tqdm, mvt
  WARNING: The scripts pyrsa-decrypt, pyrsa-encrypt, pyrsa-keygen, pyrsa-priv2pub, pyrsa-sign and pyrsa-verify are installed in '/home/root1/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pygmentize is installed in '/home/root1/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script cmark is installed in '/home/root1/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script update-tld-names is installed in '/home/root1/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tqdm is installed in '/home/root1/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts mvt-android and mvt-ios are installed in '/home/root1/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed adb-shell-0.4.0 biplist-1.0.3 commonmark-0.9.1 iOSbackup-0.9.912 libusb1-1.9.3 mvt-1.0.11 pyasn1-0.4.8 pycryptodome-3.10.1 pygments-2.9.0 rich-10.6.0 rsa-4.7.2 tld-0.12.6 tqdm-4.61.2
root1@root1-virtual-machine:~/mvt$ mvt-ios
mvt-ios: command not found
root1@root1-virtual-machine:~/mvt$

**Comment by pkirkovsky** [comment]
- Don't do this as root.
- You need to add `/home/user/.local/bin` to your path by following [these instructions](https://stackabuse.com/how-to-permanently-set-path-in-linux)
- To fix the `prompt_required` error in your first comment, just run `pip3 install click --upgrade`
- To double-check where mvt lives, try `which mvt-ios` or `which mvt-android`. If you don't get any output, that means your shell doesn't know where those commands are (it looks in the directories specified by $PATH)
- `pip3 show mvt` will also provide useful information

**Comment by BMWKingOC** [comment]
I think i got it working? Attatching imagine. please confirm if its properly installed now?
i type -mvt-ios and now get a output i think is working? 
![working1](https://user-images.githubusercontent.com/87839455/126839351-4333ac27-bd70-401a-83f3-3292a8364471.png)

**Comment by pkirkovsky** [comment]
Looks good!
