### ISSUE TITLE
You have to specify output folder problem

### ISSUE THREAD

**Issue by madabit** [mvt-project/mvt#77]
Thanks soo much. I got full solutions of my previous problems from you. However, I think it's the ending problems. It is showing:
![IMG_20210723_101212](https://user-images.githubusercontent.com/87820067/126736570-5bbb533c-96b6-4a2f-b6c9-de5bd6ea7e31.jpg)
What to do now?
How can I specify the output folder here?

**Comment by pkirkovsky** [comment]
>How can I specify the output folder here?

Specify an output folder with `--output` or `-o` followed the desired output folder

**Comment by Te-k** [comment]
@pkirkovsky is right, closing
