### ISSUE TITLE
ERROR    [mvt.android.modules.adb.rootbinaries                   ] There might be no data to extract                   by module RootBinaries: [Errno 2] No                   such file or directory: '/data/data/c                   om.termux/files/home/.android/adbkey' $

### ISSUE THREAD

**Issue by madabit** [mvt-project/mvt#79]
![IMG_20210723_102228](https://user-images.githubusercontent.com/87820067/126737245-10025330-534b-444c-876b-b3271dc6f0f6.jpg)
![IMG_20210723_102242](https://user-images.githubusercontent.com/87820067/126737246-fa7f1eba-3fdc-49ff-a786-a8e072527ac2.jpg)
How can I face these directory problems and other problems??

**Comment by madabit** [comment]
Mentionable I am not a root user

**Comment by botherder** [comment]
mvt is not meant to be run on an Android system. It is meant to be run on a desktop computer, with an Android device connected over USB.
