### ISSUE TITLE
Device is busy error

### ISSUE THREAD

**Issue by Iolaum** [mvt-project/mvt#8]
I am testing mvt on my laptop and I am getting the following error:

```
$ mvt-android download-apks --output ./download-apks --virustotal
18:07:38 CRITICAL [mvt.android.modules.adb.base] Device is busy, maybe run `adb kill-server` and try again.
```

I think adb is working ok, because afterwards I can run a complex command such as:

```
# see installed applications:
$ adb shell "pm list packages -u -3" | cut -f 2 -d ":" | sort > installed-applications-$(date +%Y%m%d).info
```
and it works ok.

I 've also tried
```
$ adb kill-server
$ adb devices
# make sure permissions are given so that adb can see the device
```
but I got the error again.

I am running this on Fedora Silverblue 34 with the latest platform-tools 31.0.2 provided from Google.
My phone is a Le eco le pro 3  (zl1) running Lineage OS 18.1 with Gapps and Magisk.

**Comment by Iolaum** [comment]
I 've also tried the same process on a family members Samsung Galaxy A40 updated with latest stock ROM device and got the same error. Getting the list of latest installed packages worked fine again.

**Comment by amirkarimi** [comment]
Same on Pixel 4 and Ubuntu 20.04. 

Changed this: https://github.com/mvt-project/mvt/blob/065a62cee1632a6e97564510886bb58397fec7bf/mvt/android/modules/adb/base.py#L64-L65

To: 

```python
except (USBErrorBusy, USBErrorAccess) as e:
    log.critical(f"Device is busy, maybe run `adb kill-server` and try again. {e}")
```

It reports:

```
CRITICAL [mvt.android.modules.adb.base] Device is busy, maybe run `adb kill-server` and try again. LIBUSB_ERROR_BUSY [-6]
```

So at least in my case, it's not access error.

**Comment by Nicceboy** [comment]
I had similar problem, and I had to make sure that ADB server daemon is not running on background.
Run `adb kill-server` but don't run `adb devices` afterwards, because it will start server again.

**Comment by davidmigloz** [comment]
In my case, it was because Android Studio was open.
