### ISSUE TITLE
LIBUSB timeout error

### ISSUE THREAD

**Issue by realunkn0wn** [mvt-project/mvt#86]
i always get this error:
07:15:27 CRITICAL [mvt.android.modules.adb.base] Could not receive data from 
                  first 149d1947 (timeout 5000ms): LIBUSB_ERROR_TIMEOUT [-7] 
idk how to solve this i am using a garbage OPPO maybe thats why pls help.

**Comment by U039b** [comment]
Please provide more details including:
* the command you run
* the output logs
Be sure that `adb devices` list the device connected to your computer.

**Comment by realunkn0wn** [comment]
I tried to run download-apks --output output
And i only get that error as the log?

**Comment by realunkn0wn** [comment]
I wanted to first get a backup from my handy but it did appear on my phone but i couldnt press make backup so i saw that he wanted to do a backup but i couldnt confirm it

**Comment by amiroff157** [comment]
Same error when I ran the `mvt-android download-apks --output` command when connected via adb.

Also when trying to run against a backup file it prints `Extracted a total of x SMS messages containing links` and doesn't tell you where to go from there... what's a STIX2 file? how to go further from here?

**Comment by amineds** [comment]
@amiroff157 to run checks against an iocs file use the option --iocs PATH_TO_IOCS.
This worked for me : mvt-android check-backup --output sms --iocs PATH_TO_IOCS  .

**Comment by amiroff157** [comment]
> @amiroff157 to run checks against an iocs file use the option --iocs
> This worked for me : mvt-android check-backup --output sms --iocs PATH_TO_IOCS .

can you recommend relevant iocs? say for the latest Signal malware?

I don't know which one to pick: https://oasis-open.github.io/cti-documentation/stix/intro

**Comment by amineds** [comment]
I used pegasus.stix2 found here https://github.com/AmnestyTech/investigations/tree/master/2021-07-18_nso

**Comment by beltet** [comment]
> I used pegasus.stix2 found here https://github.com/AmnestyTech/investigations/tree/master/2021-07-18_nso

Do you get a negative response if there were no detections? I don't get any output. Shall I assume there is no detection?

**Comment by grafixen** [comment]
A quick restart of the phone did the trick for me

**Comment by realunkn0wn** [comment]
> A quick restart of the phone did the trick for me

this didnt helped me and i do see my device on adb devices

**Comment by realunkn0wn** [comment]
ok i fixed it i didnt save the computer as authorized now it works
