### ISSUE TITLE
Loophole in license

### ISSUE THREAD

**Issue by alteholz** [mvt-project/mvt#88]
It looks like your license contains some loophole.

In case someone steals an electronic device and puts some malicious software on it, he did use the device during that process and such is a "Data Owner" according to 1.17. If you now analyze the data from this electronic device, you did not inform any Data Owner about your analysis. But as this is required according to 3.0, your license to use the software will be terminated.
You can only become compliant again after every Data Owner consents to the analysis. I doubt you will get it from the person mentioned above.
So you are no longer allowed to use this software, even to analyse other electronic devices.

One can use a computer by remotely login to it and execute some software. If executing some software on an electronic device already is some kind of usage according to 1.17, one does not even have to steal the phone but just put the malicious software on it to become a "Data Owner".

Normally you can not distinguish without analysis whether a third person infected the electronic device with some malicious software or the user did it himself.
So strictly speaking you are not allowed to analyse any electronic device in the real world unless all malicious persons consent,
Makes your software pretty useless, doesn't it?

**Comment by botherder** [comment]
I'm not a lawyer, but I'm skeptical one could successfully argue that a malicious attacker having illegitimately obtained access to a device is an entitled user of that device. It seems like a pretty stretched interpretation of the license's language. Point taken though, I will add a "legitimate" to "who made use" in the text.
