### ISSUE TITLE
[Android] Fix path to su binary

### ISSUE THREAD

**Issue by hant0508** [mvt-project/mvt#9]
Path for `su` binary is hardcoded in `_adb_check_if_root()` (in the file _android/modules/adb/base.py_) as `/sbin/su`. It's not the only possible location of this binary. On my device running Android 11 rooted with Magisk the path is `/system/bin/su`. According [this StackOverflow answer](https://stackoverflow.com/a/55105140) you should check about 40 paths where `su` binary can be placed by different root providers, or find some other way to check the device is rooted.

**Comment by botherder** [comment]
Closing this as resolved.
