### ISSUE TITLE
decrypting failing even with correct password (manifestdb? )

### ISSUE THREAD

**Issue by BMWKingOC** [mvt-project/mvt#93]
ahizzle@ahizzle-virtual-machine:~$ mvt-ios decrypt-backup -p [password] -d /home/ahizzle/decryptedbackup/ /home/ahizzle/Backup/devicepathid/
20:30:20 INFO     [mvt.ios.decrypt] Decrypting iOS backup at path               
                  /home/ahizzle/Backup/devicepathid/
                  with password                                                 
20:30:25 ERROR    [mvt.ios.decrypt] b'KEY'                                      
                  Traceback (most recent call last):                            
                    File "/home/ahizzle/.local/lib/python3.8/site-packages/mvt/i
                  os/decrypt.py", line 75, in decrypt_with_password             
                      self._backup =                                            
                  iOSbackup(udid=os.path.basename(self.backup_path),            
                    File "/home/ahizzle/.local/lib/python3.8/site-packages/iOSba
                  ckup/__init__.py", line 190, in __init__                      
                      self.getManifestDB()                                      
                    File "/home/ahizzle/.local/lib/python3.8/site-packages/iOSba
                  ckup/__init__.py", line 1037, in getManifestDB                
                      key = self.unwrapKeyForClass(manifest_class, manifest_key)
                    File "/home/ahizzle/.local/lib/python3.8/site-packages/iOSba
                  ckup/__init__.py", line 1150, in unwrapKeyForClass            
                      ck = self.classKeys[protection_class][b"KEY"]             
                  KeyError: b'KEY'                                              
         CRITICAL [mvt.ios.decrypt] Failed to decrypt backup. Did you provide   
                  the correct password?                                         
Exception ignored in: <function iOSbackup.__del__ at 0x7f53d81ef940>
Traceback (most recent call last):
  File "/home/ahizzle/.local/lib/python3.8/site-packages/iOSbackup/__init__.py", line 132, in __del__
    self.close()
  File "/home/ahizzle/.local/lib/python3.8/site-packages/iOSbackup/__init__.py", line 138, in close
    os.remove(self.manifestDB)
TypeError: remove: path should be string, bytes or os.PathLike, not NoneType

**Comment by p00perama** [comment]
> /home/ahizzle/Backup/devicepathid/
use the folder named by the UDID

**Comment by BMWKingOC** [comment]
/home/ahizzle/Backup/devicepathid/

"devicepathid" is my uid... it's a long string of letters/ numbers...

home/ahizzle/Backup/UIDID/

**Comment by BMWKingOC** [comment]
X_X

**Comment by BMWKingOC** [comment]
I'd appreciate help ):

**Comment by tasket** [comment]
I have the same problem with an iPhone 6s that is not jailbroken. I used `idevicebackup2` v1.3.0 on Debian 11 to turn on encryption and perform the backup.

Here is the stderr:
```
3:17:24 INFO     [mvt.ios.decrypt] Decrypting iOS backup at path
                  /home/user/backup/[*removed*] with password      
03:17:27 ERROR    [mvt.ios.decrypt] b'KEY'     
                  Traceback (most recent call last):
                    File "/home/user/.local/lib/python3.9/site-packages/mvt/ios/decrypt.py", line 75, in
                  decrypt_with_password
                      self._backup = iOSbackup(udid=os.path.basename(self.backup_path),
                    File "/home/user/.local/lib/python3.9/site-packages/iOSbackup/__init__.py", line 190, in
                  __init__
                      self.getManifestDB()
                    File "/home/user/.local/lib/python3.9/site-packages/iOSbackup/__init__.py", line 1037, in
                  getManifestDB
                      key = self.unwrapKeyForClass(manifest_class, manifest_key)
                    File "/home/user/.local/lib/python3.9/site-packages/iOSbackup/__init__.py", line 1150, in
                  unwrapKeyForClass
                      ck = self.classKeys[protection_class][b"KEY"]
                  KeyError: b'KEY'
         CRITICAL [mvt.ios.decrypt] Failed to decrypt backup. Did you provide the correct password?
Exception ignored in: <function iOSbackup.__del__ at 0x79e533c44280>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/iOSbackup/__init__.py", line 132, in __del__
    self.close()
  File "/home/user/.local/lib/python3.9/site-packages/iOSbackup/__init__.py", line 138, in close
    os.remove(self.manifestDB)
TypeError: remove: path should be string, bytes or os.PathLike, not NoneType
```
---

PS - Some guidance on the best way to jailbreak for this use case would be helpful.

**Comment by BMWKingOC** [comment]
glad I'm not alone @tasket 

Aint got none help sadly!

**Comment by merganon** [comment]
A quick fix is to use a password without special characters

**Comment by BMWKingOC** [comment]
> A quick fix is to use a password without special characters

so i gotta change my itunes backup password via using itunes on windows? then re do another full backup and then move that one to my linux server with a basic password?

**Comment by merganon** [comment]
> > A quick fix is to use a password without special characters
> 
> so i gotta change my itunes backup password via using itunes on windows? then re do another full backup and then move that one to my linux server with a basic password?
> 
> i originally used windows to make a full backup then SSH copied via ftp to my ubuntu vm

Correct, you set a new backup password on iTunes without special characters, then decrypt as usual with the MVT tool

**Comment by BMWKingOC** [comment]
> > > A quick fix is to use a password without special characters
> > 
> > 
> > so i gotta change my itunes backup password via using itunes on windows? then re do another full backup and then move that one to my linux server with a basic password?
> > i originally used windows to make a full backup then SSH copied via ftp to my ubuntu vm
> 
> Correct, you set a new backup password without special characters, then do a backup, then decrypt as usual with the MVT tool

wow it worked! THANK U SO MUCH
