### ISSUE TITLE
WARNING should be added in the documentation for live HTTP requests 

### ISSUE THREAD

**Issue by GelosSnake** [mvt-project/mvt#94]
Hi,

I think a warning should be added in the documentation or in the tool itself, alerting the investigator the links are going to be requested/queried from the machine. 

This can compromise an investigation or alert the attackers on the location of the investigators. 

Maybe would be nice to add tunneling option etc later on (ill see if I can add it).

Example output:
    INFO     [mvt.ios.modules.fs.safari_history] Found HTTP redirect to different domain: "tinyurl.com" -> "XXXXX.co.il"
         WARNING  [mvt.ios.modules.fs.safari_history] Redirect took less than a second! (0 milliseconds)
         INFO     [mvt.ios.modules.fs.safari_history] Found HTTP redirect to different domain: "tinyurl.com" -> "XXXXX.co.il"
         WARNING  [mvt.ios.modules.fs.safari_history] Redirect took less than a second! (0 milliseconds)
         INFO     [mvt.ios.modules.fs.safari_history] Found HTTP redirect to different domain: "tinyurl.com" -> "XXXXX.co.il"
         WARNING  [mvt.ios.modules.fs.safari_history] Redirect took less than a second! (0 milliseconds)
         INFO     [mvt.ios.modules.fs.safari_history] Found HTTP redirect to different domain: "tinyurl.com" -> "XXXXX.co.il"
         WARNING  [mvt.ios.modules.fs.safari_history] Redirect took less than a second! (0 milliseconds)

**Comment by botherder** [comment]
Those redirections are not performed live, they are statically evinced from the Safari history database correlating records and timestamps.
The only live HTTP traffic there is are attempts to resolve known shortened URLs using an HTTP HEAD request.

**Comment by GelosSnake** [comment]
My bad sorry. 
Was jumping out to me from the output
