### ISSUE TITLE
Is MVT useable under Windows ?

### ISSUE THREAD

**Issue by gittyhub2018** [mvt-project/mvt#96]
Hello,

I have seen, that MVT Need Linux or MacOS. But MVT is programmed with Python 3 and shall be useable with many OS.
Exist the possibility to use it with windows or exist any restrictions?

Thank you for your help.

Sincerely yours,
gittyhub2018

**Comment by fnaat** [comment]
I had `download-apks` running on Windows 10, but `check-adb` failed and then `download-apks` also stopped working. See issue #69

**Comment by botherder** [comment]
It's not tested on Windows, but for some people it seems to work fine with some adjustments (e.g. #61).
