### ISSUE TITLE
Location of output files ?

### ISSUE THREAD

**Issue by bhusain966** [mvt-project/mvt#99]
Greetings,

So I have installed and executed the command successfully. I have got some errors such as "unable to find the module's database" for some modules like ChromeFavicon.  But most of the other modules seems to be found and data were extracted. 

However,

I couldn't find where all there data extracted are located? I have searched mvt folder and couldn't find any. 

Can you please point where can I find results/output files ?

Thanks

**Comment by botherder** [comment]
Files are only created if you specify a folder using the `--output` argument.
Those errors are not relevant, they only indicate your backup did not have databases relevant for those particular modules.
